// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/node/v1/node.proto

package nodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server -> Node
type ServerMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // 请求 ID，用于关联响应
	Method string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // 对应现有 Client 方法名
	Body   []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`     // JSON 编码的请求体（复用现有结构体）
	// 用于取消正在进行的流式调用（如 LogsStream）
	CancelId      string `protobuf:"bytes,4,opt,name=cancel_id,json=cancelId,proto3" json:"cancel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_node_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServerMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetCancelId() string {
	if x != nil {
		return x.CancelId
	}
	return ""
}

// Node -> Server
type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 对应请求 ID（主动推送时为空）
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Body  []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"` // JSON 编码的响应体
	Error string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// 主动推送类型："log" | "traceroute_hop" | "usage_push" | "hello" | ""
	Event string `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	// node 主动推 usage 时携带，server ack 后 node 才能丢弃
	Seq           uint64 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_node_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeMessage) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NodeMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NodeMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NodeMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_proto_node_v1_node_proto protoreflect.FileDescriptor

const file_proto_node_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x18proto/node/v1/node.proto\x12\rpulse.node.v1\"h\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x1b\n" +
	"\tcancel_id\x18\x04 \x01(\tR\bcancelId\"\x7f\n" +
	"\vNodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq2T\n" +
	"\tNodeAgent\x12G\n" +
	"\aSession\x12\x1a.pulse.node.v1.NodeMessage\x1a\x1c.pulse.node.v1.ServerMessage(\x010\x01B\x1aZ\x18pulse/internal/pb/nodev1b\x06proto3"

var (
	file_proto_node_v1_node_proto_rawDescOnce sync.Once
	file_proto_node_v1_node_proto_rawDescData []byte
)

func file_proto_node_v1_node_proto_rawDescGZIP() []byte {
	file_proto_node_v1_node_proto_rawDescOnce.Do(func() {
		file_proto_node_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_v1_node_proto_rawDesc), len(file_proto_node_v1_node_proto_rawDesc)))
	})
	return file_proto_node_v1_node_proto_rawDescData
}

var file_proto_node_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_node_v1_node_proto_goTypes = []any{
	(*ServerMessage)(nil), // 0: pulse.node.v1.ServerMessage
	(*NodeMessage)(nil),   // 1: pulse.node.v1.NodeMessage
}
var file_proto_node_v1_node_proto_depIdxs = []int32{
	1, // 0: pulse.node.v1.NodeAgent.Session:input_type -> pulse.node.v1.NodeMessage
	0, // 1: pulse.node.v1.NodeAgent.Session:output_type -> pulse.node.v1.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_node_v1_node_proto_init() }
func file_proto_node_v1_node_proto_init() {
	if File_proto_node_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_v1_node_proto_rawDesc), len(file_proto_node_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_v1_node_proto_goTypes,
		DependencyIndexes: file_proto_node_v1_node_proto_depIdxs,
		MessageInfos:      file_proto_node_v1_node_proto_msgTypes,
	}.Build()
	File_proto_node_v1_node_proto = out.File
	file_proto_node_v1_node_proto_goTypes = nil
	file_proto_node_v1_node_proto_depIdxs = nil
}
