// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteAnnouncementByID = `-- name: DeleteAnnouncementByID :exec
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncementByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAnnouncementByID, id)
	return err
}

const disableAllAnnouncements = `-- name: DisableAllAnnouncements :exec
UPDATE announcements SET enabled = false, updated_at = $1
`

func (q *Queries) DisableAllAnnouncements(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.Exec(ctx, disableAllAnnouncements, updatedAt)
	return err
}

const disableAnnouncement = `-- name: DisableAnnouncement :exec
UPDATE announcements SET enabled = false, updated_at = $1 WHERE id = $2
`

type DisableAnnouncementParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) DisableAnnouncement(ctx context.Context, arg DisableAnnouncementParams) error {
	_, err := q.db.Exec(ctx, disableAnnouncement, arg.UpdatedAt, arg.ID)
	return err
}

const enableAnnouncement = `-- name: EnableAnnouncement :exec
UPDATE announcements SET enabled = true, updated_at = $1 WHERE id = $2
`

type EnableAnnouncementParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) EnableAnnouncement(ctx context.Context, arg EnableAnnouncementParams) error {
	_, err := q.db.Exec(ctx, enableAnnouncement, arg.UpdatedAt, arg.ID)
	return err
}

const getActiveAnnouncement = `-- name: GetActiveAnnouncement :one
SELECT id, title, content, enabled, created_at, updated_at
FROM announcements WHERE enabled = true LIMIT 1
`

func (q *Queries) GetActiveAnnouncement(ctx context.Context) (Announcement, error) {
	row := q.db.QueryRow(ctx, getActiveAnnouncement)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, title, content, enabled, created_at, updated_at FROM announcements WHERE id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id string) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAnnouncement = `-- name: InsertAnnouncement :exec
INSERT INTO announcements (id, title, content, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAnnouncementParams struct {
	ID        string
	Title     string
	Content   string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) error {
	_, err := q.db.Exec(ctx, insertAnnouncement,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAnnouncements = `-- name: ListAnnouncements :many
SELECT id, title, content, enabled, created_at, updated_at
FROM announcements ORDER BY created_at DESC
`

func (q *Queries) ListAnnouncements(ctx context.Context) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listAnnouncements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnnouncement = `-- name: UpdateAnnouncement :exec
UPDATE announcements SET title = $1, content = $2, enabled = $3, updated_at = $4 WHERE id = $5
`

type UpdateAnnouncementParams struct {
	Title     string
	Content   string
	Enabled   bool
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) error {
	_, err := q.db.Exec(ctx, updateAnnouncement,
		arg.Title,
		arg.Content,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
