// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cfdomain.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteCFDomainByID = `-- name: DeleteCFDomainByID :execresult
DELETE FROM cf_domains WHERE id = $1
`

func (q *Queries) DeleteCFDomainByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCFDomainByID, id)
}

const getCFDomainByID = `-- name: GetCFDomainByID :one
SELECT id, cf_token, zone_id, zone_name, COALESCE(remark, '') AS remark
FROM cf_domains WHERE id = $1
`

type GetCFDomainByIDRow struct {
	ID       string
	CfToken  string
	ZoneID   string
	ZoneName string
	Remark   string
}

func (q *Queries) GetCFDomainByID(ctx context.Context, id string) (GetCFDomainByIDRow, error) {
	row := q.db.QueryRow(ctx, getCFDomainByID, id)
	var i GetCFDomainByIDRow
	err := row.Scan(
		&i.ID,
		&i.CfToken,
		&i.ZoneID,
		&i.ZoneName,
		&i.Remark,
	)
	return i, err
}

const listCFDomains = `-- name: ListCFDomains :many
SELECT id, cf_token, zone_id, zone_name, COALESCE(remark, '') AS remark
FROM cf_domains ORDER BY id
`

type ListCFDomainsRow struct {
	ID       string
	CfToken  string
	ZoneID   string
	ZoneName string
	Remark   string
}

func (q *Queries) ListCFDomains(ctx context.Context) ([]ListCFDomainsRow, error) {
	rows, err := q.db.Query(ctx, listCFDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCFDomainsRow{}
	for rows.Next() {
		var i ListCFDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.CfToken,
			&i.ZoneID,
			&i.ZoneName,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCFDomain = `-- name: UpsertCFDomain :exec
INSERT INTO cf_domains (id, cf_token, zone_id, zone_name, remark)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(id) DO UPDATE SET
    cf_token  = excluded.cf_token,
    zone_id   = excluded.zone_id,
    zone_name = excluded.zone_name,
    remark    = excluded.remark
`

type UpsertCFDomainParams struct {
	ID       string
	CfToken  string
	ZoneID   string
	ZoneName string
	Remark   *string
}

func (q *Queries) UpsertCFDomain(ctx context.Context, arg UpsertCFDomainParams) error {
	_, err := q.db.Exec(ctx, upsertCFDomain,
		arg.ID,
		arg.CfToken,
		arg.ZoneID,
		arg.ZoneName,
		arg.Remark,
	)
	return err
}
