// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enroll_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

const cleanupExpiredEnrollTokens = `-- name: CleanupExpiredEnrollTokens :execresult
DELETE FROM enroll_tokens WHERE expires_at < $1
`

func (q *Queries) CleanupExpiredEnrollTokens(ctx context.Context, expiresAt time.Time) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cleanupExpiredEnrollTokens, expiresAt)
}

const consumeEnrollToken = `-- name: ConsumeEnrollToken :execresult
UPDATE enroll_tokens
SET consumed_at = NOW()
WHERE token = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) ConsumeEnrollToken(ctx context.Context, token string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, consumeEnrollToken, token)
}

const getEnrollToken = `-- name: GetEnrollToken :one
SELECT token, node_id, expires_at, consumed_at, created_at
FROM enroll_tokens
WHERE token = $1
`

func (q *Queries) GetEnrollToken(ctx context.Context, token string) (EnrollToken, error) {
	row := q.db.QueryRow(ctx, getEnrollToken, token)
	var i EnrollToken
	err := row.Scan(
		&i.Token,
		&i.NodeID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertEnrollToken = `-- name: InsertEnrollToken :exec

INSERT INTO enroll_tokens (token, node_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertEnrollTokenParams struct {
	Token     string
	NodeID    string
	ExpiresAt time.Time
}

// ─── Enroll Tokens ────────────────────────────────────────────────────────────
func (q *Queries) InsertEnrollToken(ctx context.Context, arg InsertEnrollTokenParams) error {
	_, err := q.db.Exec(ctx, insertEnrollToken, arg.Token, arg.NodeID, arg.ExpiresAt)
	return err
}
