// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hostexclusion.sql

package sqlcgen

import (
	"context"
)

const clearAllHostExclusionsByUser = `-- name: ClearAllHostExclusionsByUser :exec
DELETE FROM user_host_exclusions WHERE user_id = $1
`

func (q *Queries) ClearAllHostExclusionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAllHostExclusionsByUser, userID)
	return err
}

const clearHostExclusion = `-- name: ClearHostExclusion :exec
DELETE FROM user_host_exclusions WHERE user_id = $1 AND host_id = $2
`

type ClearHostExclusionParams struct {
	UserID string
	HostID string
}

func (q *Queries) ClearHostExclusion(ctx context.Context, arg ClearHostExclusionParams) error {
	_, err := q.db.Exec(ctx, clearHostExclusion, arg.UserID, arg.HostID)
	return err
}

const listHostExclusionsByUser = `-- name: ListHostExclusionsByUser :many
SELECT host_id FROM user_host_exclusions WHERE user_id = $1
`

func (q *Queries) ListHostExclusionsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listHostExclusionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHostExclusion = `-- name: SetHostExclusion :exec
INSERT INTO user_host_exclusions (user_id, host_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type SetHostExclusionParams struct {
	UserID string
	HostID string
}

func (q *Queries) SetHostExclusion(ctx context.Context, arg SetHostExclusionParams) error {
	_, err := q.db.Exec(ctx, setHostExclusion, arg.UserID, arg.HostID)
	return err
}
