// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbounds.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteHostByID = `-- name: DeleteHostByID :execresult
DELETE FROM hosts WHERE id = $1
`

func (q *Queries) DeleteHostByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteHostByID, id)
}

const deleteInboundByID = `-- name: DeleteInboundByID :execresult
DELETE FROM inbounds WHERE id = $1
`

func (q *Queries) DeleteInboundByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteInboundByID, id)
}

const deleteUserInboundsByInboundID = `-- name: DeleteUserInboundsByInboundID :exec
DELETE FROM user_inbounds WHERE inbound_id = $1
`

func (q *Queries) DeleteUserInboundsByInboundID(ctx context.Context, inboundID string) error {
	_, err := q.db.Exec(ctx, deleteUserInboundsByInboundID, inboundID)
	return err
}

const getHostByID = `-- name: GetHostByID :one
SELECT id, inbound_id, remark, address, port, sni, host, path,
       security, alpn, fingerprint, allow_insecure, mux_enable,
       reality_public_key, reality_short_id, reality_spider_x,
       country, region, network, entry, tags, relay_node_id, https_port
FROM hosts WHERE id = $1
`

func (q *Queries) GetHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRow(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.InboundID,
		&i.Remark,
		&i.Address,
		&i.Port,
		&i.Sni,
		&i.Host,
		&i.Path,
		&i.Security,
		&i.Alpn,
		&i.Fingerprint,
		&i.AllowInsecure,
		&i.MuxEnable,
		&i.RealityPublicKey,
		&i.RealityShortID,
		&i.RealitySpiderX,
		&i.Country,
		&i.Region,
		&i.Network,
		&i.Entry,
		&i.Tags,
		&i.RelayNodeID,
		&i.HttpsPort,
	)
	return i, err
}

const getInboundByID = `-- name: GetInboundByID :one
SELECT id, node_id, protocol, tag, port,
       method, password, security, reality_private_key, reality_public_key,
       reality_handshake_addr, reality_short_id, outbound_id, traffic_rate
FROM inbounds WHERE id = $1
`

func (q *Queries) GetInboundByID(ctx context.Context, id string) (Inbound, error) {
	row := q.db.QueryRow(ctx, getInboundByID, id)
	var i Inbound
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Protocol,
		&i.Tag,
		&i.Port,
		&i.Method,
		&i.Password,
		&i.Security,
		&i.RealityPrivateKey,
		&i.RealityPublicKey,
		&i.RealityHandshakeAddr,
		&i.RealityShortID,
		&i.OutboundID,
		&i.TrafficRate,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, inbound_id, remark, address, port, sni, host, path,
       security, alpn, fingerprint, allow_insecure, mux_enable,
       reality_public_key, reality_short_id, reality_spider_x,
       country, region, network, entry, tags, relay_node_id, https_port
FROM hosts ORDER BY id
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.InboundID,
			&i.Remark,
			&i.Address,
			&i.Port,
			&i.Sni,
			&i.Host,
			&i.Path,
			&i.Security,
			&i.Alpn,
			&i.Fingerprint,
			&i.AllowInsecure,
			&i.MuxEnable,
			&i.RealityPublicKey,
			&i.RealityShortID,
			&i.RealitySpiderX,
			&i.Country,
			&i.Region,
			&i.Network,
			&i.Entry,
			&i.Tags,
			&i.RelayNodeID,
			&i.HttpsPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostsByInbound = `-- name: ListHostsByInbound :many
SELECT id, inbound_id, remark, address, port, sni, host, path,
       security, alpn, fingerprint, allow_insecure, mux_enable,
       reality_public_key, reality_short_id, reality_spider_x,
       country, region, network, entry, tags, relay_node_id, https_port
FROM hosts WHERE inbound_id = $1 ORDER BY id
`

func (q *Queries) ListHostsByInbound(ctx context.Context, inboundID string) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHostsByInbound, inboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.InboundID,
			&i.Remark,
			&i.Address,
			&i.Port,
			&i.Sni,
			&i.Host,
			&i.Path,
			&i.Security,
			&i.Alpn,
			&i.Fingerprint,
			&i.AllowInsecure,
			&i.MuxEnable,
			&i.RealityPublicKey,
			&i.RealityShortID,
			&i.RealitySpiderX,
			&i.Country,
			&i.Region,
			&i.Network,
			&i.Entry,
			&i.Tags,
			&i.RelayNodeID,
			&i.HttpsPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbounds = `-- name: ListInbounds :many
SELECT id, node_id, protocol, tag, port,
       method, password, security, reality_private_key, reality_public_key,
       reality_handshake_addr, reality_short_id, outbound_id, traffic_rate
FROM inbounds ORDER BY id
`

func (q *Queries) ListInbounds(ctx context.Context) ([]Inbound, error) {
	rows, err := q.db.Query(ctx, listInbounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Protocol,
			&i.Tag,
			&i.Port,
			&i.Method,
			&i.Password,
			&i.Security,
			&i.RealityPrivateKey,
			&i.RealityPublicKey,
			&i.RealityHandshakeAddr,
			&i.RealityShortID,
			&i.OutboundID,
			&i.TrafficRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundsByNode = `-- name: ListInboundsByNode :many
SELECT id, node_id, protocol, tag, port,
       method, password, security, reality_private_key, reality_public_key,
       reality_handshake_addr, reality_short_id, outbound_id, traffic_rate
FROM inbounds WHERE node_id = $1 ORDER BY id
`

func (q *Queries) ListInboundsByNode(ctx context.Context, nodeID string) ([]Inbound, error) {
	rows, err := q.db.Query(ctx, listInboundsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbound{}
	for rows.Next() {
		var i Inbound
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Protocol,
			&i.Tag,
			&i.Port,
			&i.Method,
			&i.Password,
			&i.Security,
			&i.RealityPrivateKey,
			&i.RealityPublicKey,
			&i.RealityHandshakeAddr,
			&i.RealityShortID,
			&i.OutboundID,
			&i.TrafficRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHost = `-- name: UpsertHost :exec

INSERT INTO hosts (
    id, inbound_id, remark, address, port, sni, host, path,
    security, alpn, fingerprint, allow_insecure, mux_enable,
    reality_public_key, reality_short_id, reality_spider_x,
    country, region, network, entry, tags, relay_node_id, https_port
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
ON CONFLICT(id) DO UPDATE SET
    inbound_id         = excluded.inbound_id,
    remark             = excluded.remark,
    address            = excluded.address,
    port               = excluded.port,
    sni                = excluded.sni,
    host               = excluded.host,
    path               = excluded.path,
    security           = excluded.security,
    alpn               = excluded.alpn,
    fingerprint        = excluded.fingerprint,
    allow_insecure     = excluded.allow_insecure,
    mux_enable         = excluded.mux_enable,
    reality_public_key = excluded.reality_public_key,
    reality_short_id   = excluded.reality_short_id,
    reality_spider_x   = excluded.reality_spider_x,
    country            = excluded.country,
    region             = excluded.region,
    network            = excluded.network,
    entry              = excluded.entry,
    tags               = excluded.tags,
    relay_node_id      = excluded.relay_node_id,
    https_port   = excluded.https_port
`

type UpsertHostParams struct {
	ID               string
	InboundID        string
	Remark           string
	Address          string
	Port             int32
	Sni              string
	Host             string
	Path             string
	Security         string
	Alpn             string
	Fingerprint      string
	AllowInsecure    int32
	MuxEnable        int32
	RealityPublicKey string
	RealityShortID   string
	RealitySpiderX   string
	Country          string
	Region           string
	Network          string
	Entry            string
	Tags             string
	RelayNodeID      string
	HttpsPort        int32
}

// ─── Hosts ────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) error {
	_, err := q.db.Exec(ctx, upsertHost,
		arg.ID,
		arg.InboundID,
		arg.Remark,
		arg.Address,
		arg.Port,
		arg.Sni,
		arg.Host,
		arg.Path,
		arg.Security,
		arg.Alpn,
		arg.Fingerprint,
		arg.AllowInsecure,
		arg.MuxEnable,
		arg.RealityPublicKey,
		arg.RealityShortID,
		arg.RealitySpiderX,
		arg.Country,
		arg.Region,
		arg.Network,
		arg.Entry,
		arg.Tags,
		arg.RelayNodeID,
		arg.HttpsPort,
	)
	return err
}

const upsertInbound = `-- name: UpsertInbound :exec

INSERT INTO inbounds (
    id, node_id, protocol, tag, port,
    method, password, security, reality_private_key, reality_public_key,
    reality_handshake_addr, reality_short_id, outbound_id, traffic_rate
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT(id) DO UPDATE SET
    node_id                = excluded.node_id,
    protocol               = excluded.protocol,
    tag                    = excluded.tag,
    port                   = excluded.port,
    method                 = excluded.method,
    password               = excluded.password,
    security               = excluded.security,
    reality_private_key    = excluded.reality_private_key,
    reality_public_key     = excluded.reality_public_key,
    reality_handshake_addr = excluded.reality_handshake_addr,
    reality_short_id       = excluded.reality_short_id,
    outbound_id            = excluded.outbound_id,
    traffic_rate           = excluded.traffic_rate
`

type UpsertInboundParams struct {
	ID                   string
	NodeID               string
	Protocol             string
	Tag                  string
	Port                 int32
	Method               string
	Password             string
	Security             string
	RealityPrivateKey    string
	RealityPublicKey     string
	RealityHandshakeAddr string
	RealityShortID       string
	OutboundID           string
	TrafficRate          float64
}

// ─── Inbounds ─────────────────────────────────────────────────────────────────
func (q *Queries) UpsertInbound(ctx context.Context, arg UpsertInboundParams) error {
	_, err := q.db.Exec(ctx, upsertInbound,
		arg.ID,
		arg.NodeID,
		arg.Protocol,
		arg.Tag,
		arg.Port,
		arg.Method,
		arg.Password,
		arg.Security,
		arg.RealityPrivateKey,
		arg.RealityPublicKey,
		arg.RealityHandshakeAddr,
		arg.RealityShortID,
		arg.OutboundID,
		arg.TrafficRate,
	)
	return err
}
