// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ipsentinel.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIPSentinelConfig = `-- name: GetIPSentinelConfig :one
SELECT node_id, region_code, region_name, base_lat, base_lon, lang_params, valid_url_suffix, enable_google, enable_trust, white_urls, keywords, updated_at FROM ip_sentinel_configs WHERE node_id = $1
`

func (q *Queries) GetIPSentinelConfig(ctx context.Context, nodeID string) (IpSentinelConfig, error) {
	row := q.db.QueryRow(ctx, getIPSentinelConfig, nodeID)
	var i IpSentinelConfig
	err := row.Scan(
		&i.NodeID,
		&i.RegionCode,
		&i.RegionName,
		&i.BaseLat,
		&i.BaseLon,
		&i.LangParams,
		&i.ValidUrlSuffix,
		&i.EnableGoogle,
		&i.EnableTrust,
		&i.WhiteUrls,
		&i.Keywords,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIPSentinelRun = `-- name: InsertIPSentinelRun :exec
INSERT INTO ip_sentinel_runs (id, node_id, task_type, triggered_by, status, output, result, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertIPSentinelRunParams struct {
	ID          string
	NodeID      string
	TaskType    string
	TriggeredBy string
	Status      string
	Output      string
	Result      string
	StartedAt   time.Time
}

func (q *Queries) InsertIPSentinelRun(ctx context.Context, arg InsertIPSentinelRunParams) error {
	_, err := q.db.Exec(ctx, insertIPSentinelRun,
		arg.ID,
		arg.NodeID,
		arg.TaskType,
		arg.TriggeredBy,
		arg.Status,
		arg.Output,
		arg.Result,
		arg.StartedAt,
	)
	return err
}

const listEnabledIPSentinelConfigs = `-- name: ListEnabledIPSentinelConfigs :many
SELECT node_id, region_code, region_name, base_lat, base_lon, lang_params, valid_url_suffix, enable_google, enable_trust, white_urls, keywords, updated_at FROM ip_sentinel_configs WHERE enable_google = true OR enable_trust = true
`

func (q *Queries) ListEnabledIPSentinelConfigs(ctx context.Context) ([]IpSentinelConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledIPSentinelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpSentinelConfig{}
	for rows.Next() {
		var i IpSentinelConfig
		if err := rows.Scan(
			&i.NodeID,
			&i.RegionCode,
			&i.RegionName,
			&i.BaseLat,
			&i.BaseLon,
			&i.LangParams,
			&i.ValidUrlSuffix,
			&i.EnableGoogle,
			&i.EnableTrust,
			&i.WhiteUrls,
			&i.Keywords,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPSentinelRuns = `-- name: ListIPSentinelRuns :many
SELECT id, node_id, task_type, triggered_by, status, output, result, started_at, finished_at FROM ip_sentinel_runs WHERE node_id = $1 ORDER BY started_at DESC LIMIT 20
`

func (q *Queries) ListIPSentinelRuns(ctx context.Context, nodeID string) ([]IpSentinelRun, error) {
	rows, err := q.db.Query(ctx, listIPSentinelRuns, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IpSentinelRun{}
	for rows.Next() {
		var i IpSentinelRun
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.TaskType,
			&i.TriggeredBy,
			&i.Status,
			&i.Output,
			&i.Result,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIPSentinelRun = `-- name: UpdateIPSentinelRun :exec
UPDATE ip_sentinel_runs SET status = $1, output = $2, result = $3, finished_at = $4 WHERE id = $5
`

type UpdateIPSentinelRunParams struct {
	Status     string
	Output     string
	Result     string
	FinishedAt pgtype.Timestamptz
	ID         string
}

func (q *Queries) UpdateIPSentinelRun(ctx context.Context, arg UpdateIPSentinelRunParams) error {
	_, err := q.db.Exec(ctx, updateIPSentinelRun,
		arg.Status,
		arg.Output,
		arg.Result,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const upsertIPSentinelConfig = `-- name: UpsertIPSentinelConfig :exec
INSERT INTO ip_sentinel_configs (node_id, region_code, region_name, base_lat, base_lon, lang_params, valid_url_suffix, enable_google, enable_trust, white_urls, keywords, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (node_id) DO UPDATE SET
    region_code      = EXCLUDED.region_code,
    region_name      = EXCLUDED.region_name,
    base_lat         = EXCLUDED.base_lat,
    base_lon         = EXCLUDED.base_lon,
    lang_params      = EXCLUDED.lang_params,
    valid_url_suffix = EXCLUDED.valid_url_suffix,
    enable_google    = EXCLUDED.enable_google,
    enable_trust     = EXCLUDED.enable_trust,
    white_urls       = EXCLUDED.white_urls,
    keywords         = EXCLUDED.keywords,
    updated_at       = EXCLUDED.updated_at
`

type UpsertIPSentinelConfigParams struct {
	NodeID         string
	RegionCode     string
	RegionName     string
	BaseLat        float64
	BaseLon        float64
	LangParams     string
	ValidUrlSuffix string
	EnableGoogle   bool
	EnableTrust    bool
	WhiteUrls      string
	Keywords       string
	UpdatedAt      time.Time
}

func (q *Queries) UpsertIPSentinelConfig(ctx context.Context, arg UpsertIPSentinelConfigParams) error {
	_, err := q.db.Exec(ctx, upsertIPSentinelConfig,
		arg.NodeID,
		arg.RegionCode,
		arg.RegionName,
		arg.BaseLat,
		arg.BaseLon,
		arg.LangParams,
		arg.ValidUrlSuffix,
		arg.EnableGoogle,
		arg.EnableTrust,
		arg.WhiteUrls,
		arg.Keywords,
		arg.UpdatedAt,
	)
	return err
}
