// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ixdomain.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteIXDomainByID = `-- name: DeleteIXDomainByID :execresult
DELETE FROM ix_domains WHERE id = $1
`

func (q *Queries) DeleteIXDomainByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteIXDomainByID, id)
}

const getIXDomainByID = `-- name: GetIXDomainByID :one
SELECT id, name, domain, COALESCE(remark, '') AS remark
FROM ix_domains WHERE id = $1
`

func (q *Queries) GetIXDomainByID(ctx context.Context, id string) (IxDomain, error) {
	row := q.db.QueryRow(ctx, getIXDomainByID, id)
	var i IxDomain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Remark,
	)
	return i, err
}

const listIXDomains = `-- name: ListIXDomains :many
SELECT id, name, domain, COALESCE(remark, '') AS remark
FROM ix_domains ORDER BY name
`

func (q *Queries) ListIXDomains(ctx context.Context) ([]IxDomain, error) {
	rows, err := q.db.Query(ctx, listIXDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IxDomain{}
	for rows.Next() {
		var i IxDomain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIXDomain = `-- name: UpsertIXDomain :exec
INSERT INTO ix_domains (id, name, domain, remark)
VALUES ($1, $2, $3, $4)
ON CONFLICT(id) DO UPDATE SET
    name   = excluded.name,
    domain = excluded.domain,
    remark = excluded.remark
`

type UpsertIXDomainParams struct {
	ID     string
	Name   string
	Domain string
	Remark string
}

func (q *Queries) UpsertIXDomain(ctx context.Context, arg UpsertIXDomainParams) error {
	_, err := q.db.Exec(ctx, upsertIXDomain,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Remark,
	)
	return err
}
