// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID        string
	Title     string
	Content   string
	Enabled   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CfDomain struct {
	ID       string
	CfToken  string
	ZoneID   string
	ZoneName string
	Remark   *string
}

type Host struct {
	ID               string
	InboundID        string
	Remark           string
	Address          string
	Port             int32
	Sni              string
	Host             string
	Path             string
	Security         string
	Alpn             string
	Fingerprint      string
	AllowInsecure    int32
	MuxEnable        int32
	RealityPublicKey string
	RealityShortID   string
	RealitySpiderX   string
	Country          string
	Region           string
	Network          string
	Entry            string
	Tags             string
	RelayNodeID      string
	HttpsPort        int32
}

type Inbound struct {
	ID                   string
	NodeID               string
	Protocol             string
	Tag                  string
	Port                 int32
	Method               string
	Password             string
	Security             string
	RealityPrivateKey    string
	RealityPublicKey     string
	RealityHandshakeAddr string
	RealityShortID       string
	OutboundID           string
	TrafficRate          float64
	TargetHost           string
	TargetPort           int32
}

type IpSentinelConfig struct {
	NodeID         string
	RegionCode     string
	RegionName     string
	BaseLat        float64
	BaseLon        float64
	LangParams     string
	ValidUrlSuffix string
	EnableGoogle   bool
	EnableTrust    bool
	WhiteUrls      string
	Keywords       string
	UpdatedAt      time.Time
}

type IpSentinelRun struct {
	ID          string
	NodeID      string
	TaskType    string
	TriggeredBy string
	Status      string
	Output      string
	Result      string
	StartedAt   time.Time
	FinishedAt  pgtype.Timestamptz
}

type IxDomain struct {
	ID     string
	Name   string
	Domain string
	Remark string
}

type Node struct {
	ID            string
	Name          string
	BaseUrl       string
	UploadBytes   int64
	DownloadBytes int64
	AcmeEmail     string
	PanelDomain   string
	ExtraProxies  string
	HttpsPort     int32
	ExpireAt      *string
	PanelUrl      string
	Remark        string
	IpOverride    string
	Disabled      int32
	TlsMode       string
	IsLanding     bool
}

type NodeCheckResult struct {
	NodeID    string
	Service   string
	CheckType string
	Unlocked  int32
	Region    string
	Note      string
	CheckedAt string
}

type NodeDailyUsage struct {
	NodeID        string
	Date          string
	UploadBytes   int64
	DownloadBytes int64
}

type NodeDomain struct {
	ID         string
	NodeID     string
	CfDomainID string
	Fqdn       string
	RecordType string
	Content    string
	Proxied    bool
	SyncedAt   time.Time
}

type NodeSpeedtest struct {
	NodeID   string
	DownBps  int64
	UpBps    int64
	TestedAt string
}

type NodeUptimeLog struct {
	NodeID    string
	CheckedAt string
	Online    int32
	Running   int32
}

type Order struct {
	ID                   string
	UserID               string
	PlanID               string
	Email                string
	StripeSessionID      string
	StripeSubscriptionID string
	StripeCustomerID     string
	Status               string
	AmountCents          int32
	Currency             string
	CreatedAt            string
	PaidAt               *string
	LastInvoiceID        string
}

type Outbound struct {
	ID          string
	Name        string
	Protocol    string
	Server      string
	Username    string
	Password    string
	Method      string
	Uuid        string
	Sni         string
	PublicKey   string
	ShortID     string
	Fingerprint string
	Flow        string
}

type Plan struct {
	ID                     string
	Name                   string
	Description            string
	Type                   string
	PriceCents             int32
	Currency               string
	StripePriceID          string
	TrafficLimit           int64
	DurationDays           int32
	DataLimitResetStrategy string
	UserGroupIds           string
	SortOrder              int32
	Enabled                int32
	Mode                   string
	StockLimit             int32
	StockSold              int32
	CreatedAt              string
}

type RouteRule struct {
	ID            string
	Name          string
	RuleType      string
	Patterns      string
	OutboundID    string
	Priority      int32
	NodeIds       string
	InboundIds    string
	RuleSetUrl    string
	RuleSetFormat string
}

type Session struct {
	Token     string
	Username  string
	CreatedAt string
}

type Setting struct {
	Key   string
	Value string
}

type SubAccessLog struct {
	ID         int64
	UserID     string
	Ip         string
	UserAgent  string
	AccessedAt string
}

type Ticket struct {
	ID        string
	UserID    string
	Username  string
	Title     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TicketImage struct {
	ID         string
	TicketID   string
	Filename   string
	StoredName string
	Size       int64
	CreatedAt  time.Time
}

type TicketMessage struct {
	ID        string
	TicketID  string
	Content   string
	IsAdmin   bool
	CreatedAt time.Time
}

type TracerouteSnapshot struct {
	ID        string
	NodeID    string
	Direction string
	Target    string
	Hops      string
	Quality   string
	CreatedAt string
}

type User struct {
	ID                     string
	Username               string
	Status                 string
	Note                   string
	ExpireAt               *string
	DataLimitResetStrategy string
	TrafficLimitBytes      int64
	UploadBytes            int64
	DownloadBytes          int64
	UsedBytes              int64
	RawUploadBytes         int64
	RawDownloadBytes       int64
	OnHoldExpireAt         *string
	LastTrafficResetAt     *string
	OnlineAt               *string
	Connections            int64
	Devices                int64
	CreatedAt              string
	SubToken               string
	StripeCustomerID       string
	CurrentPlanID          string
	Email                  string
	Uuid                   string
	Secret                 string
}

type UserGroup struct {
	ID         string
	Name       string
	Remark     string
	InboundIds string
}

type UserGroupMember struct {
	GroupID string
	UserID  string
}

type UserHostExclusion struct {
	UserID string
	HostID string
}

type UserInbound struct {
	ID        string
	UserID    string
	InboundID string
	NodeID    string
	Uuid      string
	Secret    string
	CreatedAt string
	GroupID   string
}

type UserNodeDailyUsage struct {
	UserID        string
	NodeID        string
	Date          string
	UploadBytes   int64
	DownloadBytes int64
}
