// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const addNodeTraffic = `-- name: AddNodeTraffic :exec
UPDATE nodes
SET upload_bytes   = upload_bytes   + $1,
    download_bytes = download_bytes + $2
WHERE id = $3
`

type AddNodeTrafficParams struct {
	UploadBytes   int64
	DownloadBytes int64
	ID            string
}

func (q *Queries) AddNodeTraffic(ctx context.Context, arg AddNodeTrafficParams) error {
	_, err := q.db.Exec(ctx, addNodeTraffic, arg.UploadBytes, arg.DownloadBytes, arg.ID)
	return err
}

const deleteNodeByID = `-- name: DeleteNodeByID :execresult
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNodeByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteNodeByID, id)
}

const deleteNodeCheckResults = `-- name: DeleteNodeCheckResults :exec

DELETE FROM node_check_results WHERE node_id = $1
`

// ─── node_check_results ───────────────────────────────────────────────────────
func (q *Queries) DeleteNodeCheckResults(ctx context.Context, nodeID string) error {
	_, err := q.db.Exec(ctx, deleteNodeCheckResults, nodeID)
	return err
}

const deleteOldNodeDailyUsage = `-- name: DeleteOldNodeDailyUsage :exec
DELETE FROM node_daily_usage WHERE date < $1
`

func (q *Queries) DeleteOldNodeDailyUsage(ctx context.Context, date string) error {
	_, err := q.db.Exec(ctx, deleteOldNodeDailyUsage, date)
	return err
}

const deleteOldNodeUptime = `-- name: DeleteOldNodeUptime :exec
DELETE FROM node_uptime_log WHERE checked_at < $1
`

func (q *Queries) DeleteOldNodeUptime(ctx context.Context, checkedAt string) error {
	_, err := q.db.Exec(ctx, deleteOldNodeUptime, checkedAt)
	return err
}

const deleteTracerouteSnapshot = `-- name: DeleteTracerouteSnapshot :exec
DELETE FROM traceroute_snapshots WHERE id = $1
`

func (q *Queries) DeleteTracerouteSnapshot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTracerouteSnapshot, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, base_url, upload_bytes, download_bytes,
       COALESCE(acme_email, '') AS acme_email,
       COALESCE(panel_domain, '') AS panel_domain,
       COALESCE(extra_proxies, '') AS extra_proxies,
       COALESCE(https_port, 0) AS https_port,
       expire_at, panel_url, remark,
       COALESCE(ip_override, '') AS ip_override,
       COALESCE(disabled, 0) AS disabled,
       COALESCE(tls_mode, '') AS tls_mode,
       COALESCE(is_landing, TRUE) AS is_landing
FROM nodes
WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.UploadBytes,
		&i.DownloadBytes,
		&i.AcmeEmail,
		&i.PanelDomain,
		&i.ExtraProxies,
		&i.HttpsPort,
		&i.ExpireAt,
		&i.PanelUrl,
		&i.Remark,
		&i.IpOverride,
		&i.Disabled,
		&i.TlsMode,
		&i.IsLanding,
	)
	return i, err
}

const insertNodeCheckResult = `-- name: InsertNodeCheckResult :exec
INSERT INTO node_check_results (node_id, service, check_type, unlocked, region, note, checked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertNodeCheckResultParams struct {
	NodeID    string
	Service   string
	CheckType string
	Unlocked  int32
	Region    string
	Note      string
	CheckedAt string
}

func (q *Queries) InsertNodeCheckResult(ctx context.Context, arg InsertNodeCheckResultParams) error {
	_, err := q.db.Exec(ctx, insertNodeCheckResult,
		arg.NodeID,
		arg.Service,
		arg.CheckType,
		arg.Unlocked,
		arg.Region,
		arg.Note,
		arg.CheckedAt,
	)
	return err
}

const insertNodeUptime = `-- name: InsertNodeUptime :exec

INSERT INTO node_uptime_log (node_id, checked_at, online, running)
VALUES ($1, $2, $3, $4)
ON CONFLICT (node_id, checked_at) DO NOTHING
`

type InsertNodeUptimeParams struct {
	NodeID    string
	CheckedAt string
	Online    int32
	Running   int32
}

// ─── node_uptime_log ──────────────────────────────────────────────────────────
func (q *Queries) InsertNodeUptime(ctx context.Context, arg InsertNodeUptimeParams) error {
	_, err := q.db.Exec(ctx, insertNodeUptime,
		arg.NodeID,
		arg.CheckedAt,
		arg.Online,
		arg.Running,
	)
	return err
}

const insertTracerouteSnapshot = `-- name: InsertTracerouteSnapshot :exec

INSERT INTO traceroute_snapshots (id, node_id, direction, target, hops, quality, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTracerouteSnapshotParams struct {
	ID        string
	NodeID    string
	Direction string
	Target    string
	Hops      string
	Quality   string
	CreatedAt string
}

// ─── traceroute_snapshots ─────────────────────────────────────────────────────
func (q *Queries) InsertTracerouteSnapshot(ctx context.Context, arg InsertTracerouteSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertTracerouteSnapshot,
		arg.ID,
		arg.NodeID,
		arg.Direction,
		arg.Target,
		arg.Hops,
		arg.Quality,
		arg.CreatedAt,
	)
	return err
}

const listAllNodeCheckResults = `-- name: ListAllNodeCheckResults :many
SELECT node_id, service, check_type, unlocked, region, note, checked_at
FROM node_check_results
ORDER BY node_id, check_type, service
`

func (q *Queries) ListAllNodeCheckResults(ctx context.Context) ([]NodeCheckResult, error) {
	rows, err := q.db.Query(ctx, listAllNodeCheckResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeCheckResult{}
	for rows.Next() {
		var i NodeCheckResult
		if err := rows.Scan(
			&i.NodeID,
			&i.Service,
			&i.CheckType,
			&i.Unlocked,
			&i.Region,
			&i.Note,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllNodeSpeedTests = `-- name: ListAllNodeSpeedTests :many
SELECT node_id, down_bps, up_bps, tested_at FROM node_speedtest
`

func (q *Queries) ListAllNodeSpeedTests(ctx context.Context) ([]NodeSpeedtest, error) {
	rows, err := q.db.Query(ctx, listAllNodeSpeedTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSpeedtest{}
	for rows.Next() {
		var i NodeSpeedtest
		if err := rows.Scan(
			&i.NodeID,
			&i.DownBps,
			&i.UpBps,
			&i.TestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestTracerouteSnapshots = `-- name: ListLatestTracerouteSnapshots :many
SELECT id, node_id, direction, target, hops, quality, created_at
FROM traceroute_snapshots t1
WHERE NOT EXISTS (
    SELECT 1 FROM traceroute_snapshots t2
    WHERE t2.node_id   = t1.node_id
      AND t2.direction = t1.direction
      AND t2.target    = t1.target
      AND (t2.created_at > t1.created_at
           OR (t2.created_at = t1.created_at AND t2.id > t1.id))
)
ORDER BY node_id, direction, created_at DESC
`

func (q *Queries) ListLatestTracerouteSnapshots(ctx context.Context) ([]TracerouteSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestTracerouteSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TracerouteSnapshot{}
	for rows.Next() {
		var i TracerouteSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Direction,
			&i.Target,
			&i.Hops,
			&i.Quality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeDailyUsage = `-- name: ListNodeDailyUsage :many
SELECT node_id, date, upload_bytes, download_bytes
FROM node_daily_usage
WHERE date >= $1
ORDER BY date ASC
`

func (q *Queries) ListNodeDailyUsage(ctx context.Context, date string) ([]NodeDailyUsage, error) {
	rows, err := q.db.Query(ctx, listNodeDailyUsage, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDailyUsage{}
	for rows.Next() {
		var i NodeDailyUsage
		if err := rows.Scan(
			&i.NodeID,
			&i.Date,
			&i.UploadBytes,
			&i.DownloadBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeTracerouteSnapshots = `-- name: ListNodeTracerouteSnapshots :many
SELECT id, node_id, direction, target, hops, quality, created_at
FROM traceroute_snapshots
WHERE node_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNodeTracerouteSnapshotsParams struct {
	NodeID string
	Limit  int32
}

func (q *Queries) ListNodeTracerouteSnapshots(ctx context.Context, arg ListNodeTracerouteSnapshotsParams) ([]TracerouteSnapshot, error) {
	rows, err := q.db.Query(ctx, listNodeTracerouteSnapshots, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TracerouteSnapshot{}
	for rows.Next() {
		var i TracerouteSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Direction,
			&i.Target,
			&i.Hops,
			&i.Quality,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeUptimeBars = `-- name: ListNodeUptimeBars :many
SELECT node_id,
       to_char(date_trunc('hour', checked_at::timestamptz), 'YYYY-MM-DD HH24') AS period,
       COUNT(*)::bigint    AS total,
       SUM(online)::bigint AS online_sum
FROM node_uptime_log
WHERE checked_at >= $1
GROUP BY node_id, period
ORDER BY node_id, period
`

type ListNodeUptimeBarsRow struct {
	NodeID    string
	Period    string
	Total     int64
	OnlineSum int64
}

func (q *Queries) ListNodeUptimeBars(ctx context.Context, checkedAt string) ([]ListNodeUptimeBarsRow, error) {
	rows, err := q.db.Query(ctx, listNodeUptimeBars, checkedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeUptimeBarsRow{}
	for rows.Next() {
		var i ListNodeUptimeBarsRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Period,
			&i.Total,
			&i.OnlineSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeUptimeSummary = `-- name: ListNodeUptimeSummary :many
SELECT node_id,
       COUNT(*)::bigint        AS total_checks,
       SUM(online)::bigint     AS online_sum,
       SUM(running)::bigint    AS running_sum,
       MIN(checked_at)::text   AS first_at
FROM node_uptime_log
WHERE checked_at >= $1
GROUP BY node_id
`

type ListNodeUptimeSummaryRow struct {
	NodeID      string
	TotalChecks int64
	OnlineSum   int64
	RunningSum  int64
	FirstAt     string
}

func (q *Queries) ListNodeUptimeSummary(ctx context.Context, checkedAt string) ([]ListNodeUptimeSummaryRow, error) {
	rows, err := q.db.Query(ctx, listNodeUptimeSummary, checkedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeUptimeSummaryRow{}
	for rows.Next() {
		var i ListNodeUptimeSummaryRow
		if err := rows.Scan(
			&i.NodeID,
			&i.TotalChecks,
			&i.OnlineSum,
			&i.RunningSum,
			&i.FirstAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, base_url, upload_bytes, download_bytes,
       COALESCE(acme_email, '') AS acme_email,
       COALESCE(panel_domain, '') AS panel_domain,
       COALESCE(extra_proxies, '') AS extra_proxies,
       COALESCE(https_port, 0) AS https_port,
       expire_at, panel_url, remark,
       COALESCE(ip_override, '') AS ip_override,
       COALESCE(disabled, 0) AS disabled,
       COALESCE(tls_mode, '') AS tls_mode,
       COALESCE(is_landing, TRUE) AS is_landing
FROM nodes
ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.UploadBytes,
			&i.DownloadBytes,
			&i.AcmeEmail,
			&i.PanelDomain,
			&i.ExtraProxies,
			&i.HttpsPort,
			&i.ExpireAt,
			&i.PanelUrl,
			&i.Remark,
			&i.IpOverride,
			&i.Disabled,
			&i.TlsMode,
			&i.IsLanding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNode = `-- name: UpsertNode :exec

INSERT INTO nodes (id, name, base_url, expire_at, panel_url, remark, ip_override, disabled,
                   acme_email, panel_domain, extra_proxies, https_port,
                   tls_mode, is_landing)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT(id) DO UPDATE SET
    name          = excluded.name,
    base_url      = excluded.base_url,
    expire_at     = excluded.expire_at,
    panel_url     = excluded.panel_url,
    remark        = excluded.remark,
    ip_override   = excluded.ip_override,
    disabled      = excluded.disabled,
    acme_email    = excluded.acme_email,
    panel_domain  = excluded.panel_domain,
    extra_proxies = excluded.extra_proxies,
    https_port    = excluded.https_port,
    tls_mode      = excluded.tls_mode,
    is_landing    = excluded.is_landing
`

type UpsertNodeParams struct {
	ID           string
	Name         string
	BaseUrl      string
	ExpireAt     *string
	PanelUrl     string
	Remark       string
	IpOverride   string
	Disabled     int32
	AcmeEmail    string
	PanelDomain  string
	ExtraProxies string
	HttpsPort    int32
	TlsMode      string
	IsLanding    bool
}

// ─── Nodes ────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) error {
	_, err := q.db.Exec(ctx, upsertNode,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ExpireAt,
		arg.PanelUrl,
		arg.Remark,
		arg.IpOverride,
		arg.Disabled,
		arg.AcmeEmail,
		arg.PanelDomain,
		arg.ExtraProxies,
		arg.HttpsPort,
		arg.TlsMode,
		arg.IsLanding,
	)
	return err
}

const upsertNodeDailyUsage = `-- name: UpsertNodeDailyUsage :exec

INSERT INTO node_daily_usage (node_id, date, upload_bytes, download_bytes)
VALUES ($1, $2, $3, $4)
ON CONFLICT(node_id, date) DO UPDATE SET
    upload_bytes   = node_daily_usage.upload_bytes   + excluded.upload_bytes,
    download_bytes = node_daily_usage.download_bytes + excluded.download_bytes
`

type UpsertNodeDailyUsageParams struct {
	NodeID        string
	Date          string
	UploadBytes   int64
	DownloadBytes int64
}

// ─── node_daily_usage ─────────────────────────────────────────────────────────
func (q *Queries) UpsertNodeDailyUsage(ctx context.Context, arg UpsertNodeDailyUsageParams) error {
	_, err := q.db.Exec(ctx, upsertNodeDailyUsage,
		arg.NodeID,
		arg.Date,
		arg.UploadBytes,
		arg.DownloadBytes,
	)
	return err
}

const upsertNodeSpeedTest = `-- name: UpsertNodeSpeedTest :exec

INSERT INTO node_speedtest (node_id, down_bps, up_bps, tested_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT(node_id) DO UPDATE SET
    down_bps  = excluded.down_bps,
    up_bps    = excluded.up_bps,
    tested_at = excluded.tested_at
`

type UpsertNodeSpeedTestParams struct {
	NodeID   string
	DownBps  int64
	UpBps    int64
	TestedAt string
}

// ─── node_speedtest ───────────────────────────────────────────────────────────
func (q *Queries) UpsertNodeSpeedTest(ctx context.Context, arg UpsertNodeSpeedTestParams) error {
	_, err := q.db.Exec(ctx, upsertNodeSpeedTest,
		arg.NodeID,
		arg.DownBps,
		arg.UpBps,
		arg.TestedAt,
	)
	return err
}
