// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodedomain.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteNodeDomain = `-- name: DeleteNodeDomain :execresult
DELETE FROM node_domains WHERE id = $1
`

func (q *Queries) DeleteNodeDomain(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteNodeDomain, id)
}

const listNodeDomains = `-- name: ListNodeDomains :many
SELECT id, node_id, cf_domain_id, fqdn, record_type, content, proxied, synced_at
FROM node_domains ORDER BY fqdn
`

func (q *Queries) ListNodeDomains(ctx context.Context) ([]NodeDomain, error) {
	rows, err := q.db.Query(ctx, listNodeDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDomain{}
	for rows.Next() {
		var i NodeDomain
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.CfDomainID,
			&i.Fqdn,
			&i.RecordType,
			&i.Content,
			&i.Proxied,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeDomainsByCFDomain = `-- name: ListNodeDomainsByCFDomain :many
SELECT id, node_id, cf_domain_id, fqdn, record_type, content, proxied, synced_at
FROM node_domains WHERE cf_domain_id = $1 ORDER BY fqdn
`

func (q *Queries) ListNodeDomainsByCFDomain(ctx context.Context, cfDomainID string) ([]NodeDomain, error) {
	rows, err := q.db.Query(ctx, listNodeDomainsByCFDomain, cfDomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDomain{}
	for rows.Next() {
		var i NodeDomain
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.CfDomainID,
			&i.Fqdn,
			&i.RecordType,
			&i.Content,
			&i.Proxied,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeDomainNode = `-- name: UpdateNodeDomainNode :one
UPDATE node_domains SET node_id = $2
WHERE id = $1
RETURNING id, node_id, cf_domain_id, fqdn, record_type, content, proxied, synced_at
`

type UpdateNodeDomainNodeParams struct {
	ID     string
	NodeID string
}

func (q *Queries) UpdateNodeDomainNode(ctx context.Context, arg UpdateNodeDomainNodeParams) (NodeDomain, error) {
	row := q.db.QueryRow(ctx, updateNodeDomainNode, arg.ID, arg.NodeID)
	var i NodeDomain
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.CfDomainID,
		&i.Fqdn,
		&i.RecordType,
		&i.Content,
		&i.Proxied,
		&i.SyncedAt,
	)
	return i, err
}

const upsertNodeDomain = `-- name: UpsertNodeDomain :one
INSERT INTO node_domains (id, node_id, cf_domain_id, fqdn, record_type, content, proxied, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT(fqdn) DO UPDATE SET
    node_id     = excluded.node_id,
    cf_domain_id = excluded.cf_domain_id,
    record_type = excluded.record_type,
    content     = excluded.content,
    proxied     = excluded.proxied,
    synced_at   = NOW()
RETURNING id, node_id, cf_domain_id, fqdn, record_type, content, proxied, synced_at
`

type UpsertNodeDomainParams struct {
	ID         string
	NodeID     string
	CfDomainID string
	Fqdn       string
	RecordType string
	Content    string
	Proxied    bool
}

func (q *Queries) UpsertNodeDomain(ctx context.Context, arg UpsertNodeDomainParams) (NodeDomain, error) {
	row := q.db.QueryRow(ctx, upsertNodeDomain,
		arg.ID,
		arg.NodeID,
		arg.CfDomainID,
		arg.Fqdn,
		arg.RecordType,
		arg.Content,
		arg.Proxied,
	)
	var i NodeDomain
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.CfDomainID,
		&i.Fqdn,
		&i.RecordType,
		&i.Content,
		&i.Proxied,
		&i.SyncedAt,
	)
	return i, err
}
