// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const claimInvoice = `-- name: ClaimInvoice :execresult
UPDATE orders SET last_invoice_id = $1
WHERE id = $2 AND COALESCE(last_invoice_id, '') != $1
`

type ClaimInvoiceParams struct {
	LastInvoiceID string
	ID            string
}

func (q *Queries) ClaimInvoice(ctx context.Context, arg ClaimInvoiceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, claimInvoice, arg.LastInvoiceID, arg.ID)
}

const deleteOrderByID = `-- name: DeleteOrderByID :execresult
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrderByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOrderByID, id)
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Email,
		&i.StripeSessionID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.PaidAt,
		&i.LastInvoiceID,
	)
	return i, err
}

const getOrderByStripeSession = `-- name: GetOrderByStripeSession :one
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders WHERE stripe_session_id = $1
`

func (q *Queries) GetOrderByStripeSession(ctx context.Context, stripeSessionID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByStripeSession, stripeSessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Email,
		&i.StripeSessionID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.PaidAt,
		&i.LastInvoiceID,
	)
	return i, err
}

const getOrderByStripeSubscription = `-- name: GetOrderByStripeSubscription :one
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders WHERE stripe_subscription_id = $1
`

func (q *Queries) GetOrderByStripeSubscription(ctx context.Context, stripeSubscriptionID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByStripeSubscription, stripeSubscriptionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Email,
		&i.StripeSessionID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.PaidAt,
		&i.LastInvoiceID,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Email,
			&i.StripeSessionID,
			&i.StripeSubscriptionID,
			&i.StripeCustomerID,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.CreatedAt,
			&i.PaidAt,
			&i.LastInvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEmail = `-- name: ListOrdersByEmail :many
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders WHERE email = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByEmail(ctx context.Context, email string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Email,
			&i.StripeSessionID,
			&i.StripeSubscriptionID,
			&i.StripeCustomerID,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.CreatedAt,
			&i.PaidAt,
			&i.LastInvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, plan_id, email, stripe_session_id,
       stripe_subscription_id, stripe_customer_id,
       status, amount_cents, currency, created_at, paid_at, last_invoice_id
FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID string) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Email,
			&i.StripeSessionID,
			&i.StripeSubscriptionID,
			&i.StripeCustomerID,
			&i.Status,
			&i.AmountCents,
			&i.Currency,
			&i.CreatedAt,
			&i.PaidAt,
			&i.LastInvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrder = `-- name: UpsertOrder :exec
INSERT INTO orders (
    id, user_id, plan_id, email, stripe_session_id,
    stripe_subscription_id, stripe_customer_id,
    status, amount_cents, currency, created_at, paid_at, last_invoice_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT(id) DO UPDATE SET
    user_id                = excluded.user_id,
    plan_id                = excluded.plan_id,
    email                  = excluded.email,
    stripe_session_id      = excluded.stripe_session_id,
    stripe_subscription_id = excluded.stripe_subscription_id,
    stripe_customer_id     = excluded.stripe_customer_id,
    status                 = excluded.status,
    amount_cents           = excluded.amount_cents,
    currency               = excluded.currency,
    created_at             = excluded.created_at,
    paid_at                = excluded.paid_at,
    last_invoice_id        = excluded.last_invoice_id
`

type UpsertOrderParams struct {
	ID                   string
	UserID               string
	PlanID               string
	Email                string
	StripeSessionID      string
	StripeSubscriptionID string
	StripeCustomerID     string
	Status               string
	AmountCents          int32
	Currency             string
	CreatedAt            string
	PaidAt               *string
	LastInvoiceID        string
}

func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) error {
	_, err := q.db.Exec(ctx, upsertOrder,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.Email,
		arg.StripeSessionID,
		arg.StripeSubscriptionID,
		arg.StripeCustomerID,
		arg.Status,
		arg.AmountCents,
		arg.Currency,
		arg.CreatedAt,
		arg.PaidAt,
		arg.LastInvoiceID,
	)
	return err
}
