// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbounds.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteOutboundByID = `-- name: DeleteOutboundByID :execresult
DELETE FROM outbounds WHERE id = $1
`

func (q *Queries) DeleteOutboundByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOutboundByID, id)
}

const getOutboundByID = `-- name: GetOutboundByID :one
SELECT id, name, protocol, server, username, password, method, uuid, sni, public_key, short_id, fingerprint, COALESCE(flow, '') AS flow
FROM outbounds WHERE id = $1
`

func (q *Queries) GetOutboundByID(ctx context.Context, id string) (Outbound, error) {
	row := q.db.QueryRow(ctx, getOutboundByID, id)
	var i Outbound
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Protocol,
		&i.Server,
		&i.Username,
		&i.Password,
		&i.Method,
		&i.Uuid,
		&i.Sni,
		&i.PublicKey,
		&i.ShortID,
		&i.Fingerprint,
		&i.Flow,
	)
	return i, err
}

const listOutbounds = `-- name: ListOutbounds :many
SELECT id, name, protocol, server, username, password, method, uuid, sni, public_key, short_id, fingerprint, COALESCE(flow, '') AS flow
FROM outbounds ORDER BY id
`

func (q *Queries) ListOutbounds(ctx context.Context) ([]Outbound, error) {
	rows, err := q.db.Query(ctx, listOutbounds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbound{}
	for rows.Next() {
		var i Outbound
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Protocol,
			&i.Server,
			&i.Username,
			&i.Password,
			&i.Method,
			&i.Uuid,
			&i.Sni,
			&i.PublicKey,
			&i.ShortID,
			&i.Fingerprint,
			&i.Flow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOutbound = `-- name: UpsertOutbound :exec
INSERT INTO outbounds (id, name, protocol, server, username, password, method, uuid, sni, public_key, short_id, fingerprint, flow)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT(id) DO UPDATE SET
    name        = excluded.name,
    protocol    = excluded.protocol,
    server      = excluded.server,
    username    = excluded.username,
    password    = excluded.password,
    method      = excluded.method,
    uuid        = excluded.uuid,
    sni         = excluded.sni,
    public_key  = excluded.public_key,
    short_id    = excluded.short_id,
    fingerprint = excluded.fingerprint,
    flow        = excluded.flow
`

type UpsertOutboundParams struct {
	ID          string
	Name        string
	Protocol    string
	Server      string
	Username    string
	Password    string
	Method      string
	Uuid        string
	Sni         string
	PublicKey   string
	ShortID     string
	Fingerprint string
	Flow        string
}

func (q *Queries) UpsertOutbound(ctx context.Context, arg UpsertOutboundParams) error {
	_, err := q.db.Exec(ctx, upsertOutbound,
		arg.ID,
		arg.Name,
		arg.Protocol,
		arg.Server,
		arg.Username,
		arg.Password,
		arg.Method,
		arg.Uuid,
		arg.Sni,
		arg.PublicKey,
		arg.ShortID,
		arg.Fingerprint,
		arg.Flow,
	)
	return err
}
