// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deletePlanByID = `-- name: DeletePlanByID :execresult
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlanByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deletePlanByID, id)
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, description, type, price_cents, currency,
       stripe_price_id, traffic_limit, duration_days,
       data_limit_reset_strategy, user_group_ids, sort_order, enabled, mode,
       stock_limit, stock_sold, created_at
FROM plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.PriceCents,
		&i.Currency,
		&i.StripePriceID,
		&i.TrafficLimit,
		&i.DurationDays,
		&i.DataLimitResetStrategy,
		&i.UserGroupIds,
		&i.SortOrder,
		&i.Enabled,
		&i.Mode,
		&i.StockLimit,
		&i.StockSold,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPlanStockSold = `-- name: IncrementPlanStockSold :execresult
UPDATE plans SET stock_sold = stock_sold + 1
WHERE id = $1 AND (stock_limit = -1 OR stock_sold < stock_limit)
`

func (q *Queries) IncrementPlanStockSold(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, incrementPlanStockSold, id)
}

const listEnabledPlans = `-- name: ListEnabledPlans :many
SELECT id, name, description, type, price_cents, currency,
       stripe_price_id, traffic_limit, duration_days,
       data_limit_reset_strategy, user_group_ids, sort_order, enabled, mode,
       stock_limit, stock_sold, created_at
FROM plans WHERE enabled = 1 ORDER BY sort_order, id
`

func (q *Queries) ListEnabledPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listEnabledPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.PriceCents,
			&i.Currency,
			&i.StripePriceID,
			&i.TrafficLimit,
			&i.DurationDays,
			&i.DataLimitResetStrategy,
			&i.UserGroupIds,
			&i.SortOrder,
			&i.Enabled,
			&i.Mode,
			&i.StockLimit,
			&i.StockSold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPlansByMode = `-- name: ListEnabledPlansByMode :many
SELECT id, name, description, type, price_cents, currency,
       stripe_price_id, traffic_limit, duration_days,
       data_limit_reset_strategy, user_group_ids, sort_order, enabled, mode,
       stock_limit, stock_sold, created_at
FROM plans WHERE enabled = 1 AND mode = $1 ORDER BY sort_order, id
`

func (q *Queries) ListEnabledPlansByMode(ctx context.Context, mode string) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listEnabledPlansByMode, mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.PriceCents,
			&i.Currency,
			&i.StripePriceID,
			&i.TrafficLimit,
			&i.DurationDays,
			&i.DataLimitResetStrategy,
			&i.UserGroupIds,
			&i.SortOrder,
			&i.Enabled,
			&i.Mode,
			&i.StockLimit,
			&i.StockSold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, description, type, price_cents, currency,
       stripe_price_id, traffic_limit, duration_days,
       data_limit_reset_strategy, user_group_ids, sort_order, enabled, mode,
       stock_limit, stock_sold, created_at
FROM plans ORDER BY sort_order, id
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.PriceCents,
			&i.Currency,
			&i.StripePriceID,
			&i.TrafficLimit,
			&i.DurationDays,
			&i.DataLimitResetStrategy,
			&i.UserGroupIds,
			&i.SortOrder,
			&i.Enabled,
			&i.Mode,
			&i.StockLimit,
			&i.StockSold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlan = `-- name: UpsertPlan :exec
INSERT INTO plans (
    id, name, description, type, price_cents, currency,
    stripe_price_id, traffic_limit, duration_days,
    data_limit_reset_strategy, user_group_ids, sort_order, enabled, mode,
    stock_limit, stock_sold, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT(id) DO UPDATE SET
    name                      = excluded.name,
    description               = excluded.description,
    type                      = excluded.type,
    price_cents               = excluded.price_cents,
    currency                  = excluded.currency,
    stripe_price_id           = excluded.stripe_price_id,
    traffic_limit             = excluded.traffic_limit,
    duration_days             = excluded.duration_days,
    data_limit_reset_strategy = excluded.data_limit_reset_strategy,
    user_group_ids               = excluded.user_group_ids,
    sort_order                = excluded.sort_order,
    enabled                   = excluded.enabled,
    mode                      = excluded.mode,
    stock_limit               = excluded.stock_limit,
    stock_sold                = excluded.stock_sold,
    created_at                = excluded.created_at
`

type UpsertPlanParams struct {
	ID                     string
	Name                   string
	Description            string
	Type                   string
	PriceCents             int32
	Currency               string
	StripePriceID          string
	TrafficLimit           int64
	DurationDays           int32
	DataLimitResetStrategy string
	UserGroupIds           string
	SortOrder              int32
	Enabled                int32
	Mode                   string
	StockLimit             int32
	StockSold              int32
	CreatedAt              string
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) error {
	_, err := q.db.Exec(ctx, upsertPlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.PriceCents,
		arg.Currency,
		arg.StripePriceID,
		arg.TrafficLimit,
		arg.DurationDays,
		arg.DataLimitResetStrategy,
		arg.UserGroupIds,
		arg.SortOrder,
		arg.Enabled,
		arg.Mode,
		arg.StockLimit,
		arg.StockSold,
		arg.CreatedAt,
	)
	return err
}
