// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	AddNodeTraffic(ctx context.Context, arg AddNodeTrafficParams) error
	AddUserGroupMember(ctx context.Context, arg AddUserGroupMemberParams) error
	ClaimInvoice(ctx context.Context, arg ClaimInvoiceParams) (pgconn.CommandTag, error)
	ClearAllHostExclusionsByUser(ctx context.Context, userID string) error
	ClearHostExclusion(ctx context.Context, arg ClearHostExclusionParams) error
	CountUsersByInbound(ctx context.Context) ([]CountUsersByInboundRow, error)
	DeleteAllInboundsForGroup(ctx context.Context, groupID string) error
	DeleteAllUserGroupMembers(ctx context.Context, groupID string) error
	DeleteAnnouncementByID(ctx context.Context, id string) error
	DeleteCFDomainByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteGroupUserInbounds(ctx context.Context, arg DeleteGroupUserInboundsParams) error
	DeleteHostByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteIXDomainByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteInboundByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteNodeByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	// ─── node_check_results ───────────────────────────────────────────────────────
	DeleteNodeCheckResults(ctx context.Context, nodeID string) error
	DeleteNodeDomain(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteOldNodeDailyUsage(ctx context.Context, date string) error
	DeleteOldNodeUptime(ctx context.Context, checkedAt string) error
	DeleteOrderByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteOutboundByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeletePlanByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteRouteRuleByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteSession(ctx context.Context, token string) error
	DeleteSubAccessLogsByUserID(ctx context.Context, userID string) error
	DeleteTracerouteSnapshot(ctx context.Context, id string) error
	DeleteUserByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteUserGroupByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteUserInboundByID(ctx context.Context, id string) (pgconn.CommandTag, error)
	DeleteUserInboundsByInboundID(ctx context.Context, inboundID string) error
	DeleteUserInboundsByUserID(ctx context.Context, userID string) error
	DeleteUserInboundsByUserIDTx(ctx context.Context, userID string) error
	DeleteUserNodeDailyUsageByUserID(ctx context.Context, userID string) error
	DisableAllAnnouncements(ctx context.Context, updatedAt time.Time) error
	DisableAnnouncement(ctx context.Context, arg DisableAnnouncementParams) error
	EnableAnnouncement(ctx context.Context, arg EnableAnnouncementParams) error
	GetActiveAnnouncement(ctx context.Context) (Announcement, error)
	GetAnnouncementByID(ctx context.Context, id string) (Announcement, error)
	GetCFDomainByID(ctx context.Context, id string) (GetCFDomainByIDRow, error)
	GetHostByID(ctx context.Context, id string) (Host, error)
	GetIPSentinelConfig(ctx context.Context, nodeID string) (IpSentinelConfig, error)
	GetIXDomainByID(ctx context.Context, id string) (IxDomain, error)
	GetInboundByID(ctx context.Context, id string) (Inbound, error)
	GetNodeByID(ctx context.Context, id string) (Node, error)
	GetOrderByID(ctx context.Context, id string) (Order, error)
	GetOrderByStripeSession(ctx context.Context, stripeSessionID string) (Order, error)
	GetOrderByStripeSubscription(ctx context.Context, stripeSubscriptionID string) (Order, error)
	GetOutboundByID(ctx context.Context, id string) (Outbound, error)
	GetPlanByID(ctx context.Context, id string) (Plan, error)
	GetRouteRuleByID(ctx context.Context, id string) (GetRouteRuleByIDRow, error)
	GetSessionUsername(ctx context.Context, token string) (string, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetTicketByID(ctx context.Context, id string) (Ticket, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID string) (User, error)
	GetUserBySubToken(ctx context.Context, subToken string) (User, error)
	GetUserGroupByID(ctx context.Context, id string) (UserGroup, error)
	GetUserInboundByID(ctx context.Context, id string) (UserInbound, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error)
	IncrementPlanStockSold(ctx context.Context, id string) (pgconn.CommandTag, error)
	InsertAnnouncement(ctx context.Context, arg InsertAnnouncementParams) error
	InsertIPSentinelRun(ctx context.Context, arg InsertIPSentinelRunParams) error
	InsertNodeCheckResult(ctx context.Context, arg InsertNodeCheckResultParams) error
	// ─── node_uptime_log ──────────────────────────────────────────────────────────
	InsertNodeUptime(ctx context.Context, arg InsertNodeUptimeParams) error
	// ─── sub_access_logs ──────────────────────────────────────────────────────────
	InsertSubAccessLog(ctx context.Context, arg InsertSubAccessLogParams) error
	InsertTicket(ctx context.Context, arg InsertTicketParams) error
	InsertTicketImage(ctx context.Context, arg InsertTicketImageParams) error
	InsertTicketMessage(ctx context.Context, arg InsertTicketMessageParams) error
	// ─── traceroute_snapshots ─────────────────────────────────────────────────────
	InsertTracerouteSnapshot(ctx context.Context, arg InsertTracerouteSnapshotParams) error
	ListActiveUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error)
	ListAllNodeCheckResults(ctx context.Context) ([]NodeCheckResult, error)
	ListAllNodeSpeedTests(ctx context.Context) ([]NodeSpeedtest, error)
	ListAnnouncements(ctx context.Context) ([]Announcement, error)
	ListCFDomains(ctx context.Context) ([]ListCFDomainsRow, error)
	ListDirectUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error)
	ListEnabledIPSentinelConfigs(ctx context.Context) ([]IpSentinelConfig, error)
	ListEnabledPlans(ctx context.Context) ([]Plan, error)
	ListEnabledPlansByMode(ctx context.Context, mode string) ([]Plan, error)
	ListHostExclusionsByUser(ctx context.Context, userID string) ([]string, error)
	ListHosts(ctx context.Context) ([]Host, error)
	ListHostsByInbound(ctx context.Context, inboundID string) ([]Host, error)
	ListIPSentinelRuns(ctx context.Context, nodeID string) ([]IpSentinelRun, error)
	ListIXDomains(ctx context.Context) ([]IxDomain, error)
	ListInbounds(ctx context.Context) ([]Inbound, error)
	ListInboundsByNode(ctx context.Context, nodeID string) ([]Inbound, error)
	ListLatestTracerouteSnapshots(ctx context.Context) ([]TracerouteSnapshot, error)
	ListNodeDailyUsage(ctx context.Context, date string) ([]NodeDailyUsage, error)
	ListNodeDomains(ctx context.Context) ([]NodeDomain, error)
	ListNodeDomainsByCFDomain(ctx context.Context, cfDomainID string) ([]NodeDomain, error)
	ListNodeTracerouteSnapshots(ctx context.Context, arg ListNodeTracerouteSnapshotsParams) ([]TracerouteSnapshot, error)
	ListNodeUptimeBars(ctx context.Context, checkedAt string) ([]ListNodeUptimeBarsRow, error)
	ListNodeUptimeSummary(ctx context.Context, checkedAt string) ([]ListNodeUptimeSummaryRow, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListOrdersByEmail(ctx context.Context, email string) ([]Order, error)
	ListOrdersByUser(ctx context.Context, userID string) ([]Order, error)
	ListOutbounds(ctx context.Context) ([]Outbound, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListRouteRules(ctx context.Context) ([]ListRouteRulesRow, error)
	ListSubAccessLogs(ctx context.Context, arg ListSubAccessLogsParams) ([]SubAccessLog, error)
	ListTicketImages(ctx context.Context, ticketID string) ([]TicketImage, error)
	ListTicketMessages(ctx context.Context, ticketID string) ([]TicketMessage, error)
	ListTickets(ctx context.Context) ([]Ticket, error)
	ListTicketsByUser(ctx context.Context, userID string) ([]Ticket, error)
	ListTodayNodeUserStats(ctx context.Context, arg ListTodayNodeUserStatsParams) ([]ListTodayNodeUserStatsRow, error)
	ListTodayUserNodeStats(ctx context.Context, arg ListTodayUserNodeStatsParams) ([]ListTodayUserNodeStatsRow, error)
	ListTodayUserStats(ctx context.Context, arg ListTodayUserStatsParams) ([]ListTodayUserStatsRow, error)
	ListUserDailyUsage(ctx context.Context, arg ListUserDailyUsageParams) ([]ListUserDailyUsageRow, error)
	ListUserGroupMembers(ctx context.Context, groupID string) ([]string, error)
	ListUserGroups(ctx context.Context) ([]UserGroup, error)
	ListUserGroupsByUser(ctx context.Context, userID string) ([]string, error)
	ListUserInboundsByInbound(ctx context.Context, inboundID string) ([]UserInbound, error)
	ListUserInboundsByNode(ctx context.Context, nodeID string) ([]UserInbound, error)
	ListUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error)
	ListUserNodeUsage(ctx context.Context, userID string) ([]ListUserNodeUsageRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveUserGroupMember(ctx context.Context, arg RemoveUserGroupMemberParams) error
	SetHostExclusion(ctx context.Context, arg SetHostExclusionParams) error
	SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error
	// 插入后调用，保留每个用户最近 $2 条，超出部分按 id 升序删除（即最旧的先删）
	TrimSubAccessLogsByUser(ctx context.Context, arg TrimSubAccessLogsByUserParams) error
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) error
	UpdateIPSentinelRun(ctx context.Context, arg UpdateIPSentinelRunParams) error
	UpdateNodeDomainNode(ctx context.Context, arg UpdateNodeDomainNodeParams) (NodeDomain, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error
	UpdateTicketUpdatedAt(ctx context.Context, arg UpdateTicketUpdatedAtParams) error
	UpdateUserInboundsNodeID(ctx context.Context, arg UpdateUserInboundsNodeIDParams) error
	UpsertCFDomain(ctx context.Context, arg UpsertCFDomainParams) error
	UpsertGroupUserInbound(ctx context.Context, arg UpsertGroupUserInboundParams) error
	// ─── Hosts ────────────────────────────────────────────────────────────────────
	UpsertHost(ctx context.Context, arg UpsertHostParams) error
	UpsertIPSentinelConfig(ctx context.Context, arg UpsertIPSentinelConfigParams) error
	UpsertIXDomain(ctx context.Context, arg UpsertIXDomainParams) error
	// ─── Inbounds ─────────────────────────────────────────────────────────────────
	UpsertInbound(ctx context.Context, arg UpsertInboundParams) error
	// ─── Nodes ────────────────────────────────────────────────────────────────────
	UpsertNode(ctx context.Context, arg UpsertNodeParams) error
	// ─── node_daily_usage ─────────────────────────────────────────────────────────
	UpsertNodeDailyUsage(ctx context.Context, arg UpsertNodeDailyUsageParams) error
	UpsertNodeDomain(ctx context.Context, arg UpsertNodeDomainParams) (NodeDomain, error)
	// ─── node_speedtest ───────────────────────────────────────────────────────────
	UpsertNodeSpeedTest(ctx context.Context, arg UpsertNodeSpeedTestParams) error
	UpsertOrder(ctx context.Context, arg UpsertOrderParams) error
	UpsertOutbound(ctx context.Context, arg UpsertOutboundParams) error
	UpsertPlan(ctx context.Context, arg UpsertPlanParams) error
	UpsertRouteRule(ctx context.Context, arg UpsertRouteRuleParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	// ─── Users ────────────────────────────────────────────────────────────────────
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	UpsertUserGroup(ctx context.Context, arg UpsertUserGroupParams) error
	// ─── UserInbounds ─────────────────────────────────────────────────────────────
	UpsertUserInbound(ctx context.Context, arg UpsertUserInboundParams) error
	// ─── user_node_daily_usage ────────────────────────────────────────────────────
	UpsertUserNodeTraffic(ctx context.Context, arg UpsertUserNodeTrafficParams) error
}

var _ Querier = (*Queries)(nil)
