// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routerules.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteRouteRuleByID = `-- name: DeleteRouteRuleByID :execresult
DELETE FROM route_rules WHERE id = $1
`

func (q *Queries) DeleteRouteRuleByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteRouteRuleByID, id)
}

const getRouteRuleByID = `-- name: GetRouteRuleByID :one
SELECT id, name, rule_type, patterns, outbound_id, priority, rule_set_url, rule_set_format, node_ids, inbound_ids
FROM route_rules WHERE id = $1
`

type GetRouteRuleByIDRow struct {
	ID            string
	Name          string
	RuleType      string
	Patterns      string
	OutboundID    string
	Priority      int32
	RuleSetUrl    string
	RuleSetFormat string
	NodeIds       string
	InboundIds    string
}

func (q *Queries) GetRouteRuleByID(ctx context.Context, id string) (GetRouteRuleByIDRow, error) {
	row := q.db.QueryRow(ctx, getRouteRuleByID, id)
	var i GetRouteRuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuleType,
		&i.Patterns,
		&i.OutboundID,
		&i.Priority,
		&i.RuleSetUrl,
		&i.RuleSetFormat,
		&i.NodeIds,
		&i.InboundIds,
	)
	return i, err
}

const listRouteRules = `-- name: ListRouteRules :many
SELECT id, name, rule_type, patterns, outbound_id, priority, rule_set_url, rule_set_format, node_ids, inbound_ids
FROM route_rules ORDER BY priority, id
`

type ListRouteRulesRow struct {
	ID            string
	Name          string
	RuleType      string
	Patterns      string
	OutboundID    string
	Priority      int32
	RuleSetUrl    string
	RuleSetFormat string
	NodeIds       string
	InboundIds    string
}

func (q *Queries) ListRouteRules(ctx context.Context) ([]ListRouteRulesRow, error) {
	rows, err := q.db.Query(ctx, listRouteRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteRulesRow{}
	for rows.Next() {
		var i ListRouteRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuleType,
			&i.Patterns,
			&i.OutboundID,
			&i.Priority,
			&i.RuleSetUrl,
			&i.RuleSetFormat,
			&i.NodeIds,
			&i.InboundIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRouteRule = `-- name: UpsertRouteRule :exec
INSERT INTO route_rules (id, name, rule_type, patterns, outbound_id, priority, rule_set_url, rule_set_format, node_ids, inbound_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT(id) DO UPDATE SET
    name            = excluded.name,
    rule_type       = excluded.rule_type,
    patterns        = excluded.patterns,
    outbound_id     = excluded.outbound_id,
    priority        = excluded.priority,
    rule_set_url    = excluded.rule_set_url,
    rule_set_format = excluded.rule_set_format,
    node_ids        = excluded.node_ids,
    inbound_ids     = excluded.inbound_ids
`

type UpsertRouteRuleParams struct {
	ID            string
	Name          string
	RuleType      string
	Patterns      string
	OutboundID    string
	Priority      int32
	RuleSetUrl    string
	RuleSetFormat string
	NodeIds       string
	InboundIds    string
}

func (q *Queries) UpsertRouteRule(ctx context.Context, arg UpsertRouteRuleParams) error {
	_, err := q.db.Exec(ctx, upsertRouteRule,
		arg.ID,
		arg.Name,
		arg.RuleType,
		arg.Patterns,
		arg.OutboundID,
		arg.Priority,
		arg.RuleSetUrl,
		arg.RuleSetFormat,
		arg.NodeIds,
		arg.InboundIds,
	)
	return err
}
