// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getSessionUsername = `-- name: GetSessionUsername :one
SELECT username FROM sessions WHERE token = $1
`

func (q *Queries) GetSessionUsername(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, getSessionUsername, token)
	var username string
	err := row.Scan(&username)
	return username, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (token, username, created_at) VALUES ($1, $2, $3)
ON CONFLICT(token) DO UPDATE SET username = excluded.username, created_at = excluded.created_at
`

type UpsertSessionParams struct {
	Token     string
	Username  string
	CreatedAt string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession, arg.Token, arg.Username, arg.CreatedAt)
	return err
}
