// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package sqlcgen

import (
	"context"
	"time"
)

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, user_id, username, title, status, created_at, updated_at
FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :exec
INSERT INTO tickets (id, user_id, username, title, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTicketParams struct {
	ID        string
	UserID    string
	Username  string
	Title     string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) error {
	_, err := q.db.Exec(ctx, insertTicket,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.Title,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTicketImage = `-- name: InsertTicketImage :exec
INSERT INTO ticket_images (id, ticket_id, filename, stored_name, size, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTicketImageParams struct {
	ID         string
	TicketID   string
	Filename   string
	StoredName string
	Size       int64
	CreatedAt  time.Time
}

func (q *Queries) InsertTicketImage(ctx context.Context, arg InsertTicketImageParams) error {
	_, err := q.db.Exec(ctx, insertTicketImage,
		arg.ID,
		arg.TicketID,
		arg.Filename,
		arg.StoredName,
		arg.Size,
		arg.CreatedAt,
	)
	return err
}

const insertTicketMessage = `-- name: InsertTicketMessage :exec
INSERT INTO ticket_messages (id, ticket_id, content, is_admin, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertTicketMessageParams struct {
	ID        string
	TicketID  string
	Content   string
	IsAdmin   bool
	CreatedAt time.Time
}

func (q *Queries) InsertTicketMessage(ctx context.Context, arg InsertTicketMessageParams) error {
	_, err := q.db.Exec(ctx, insertTicketMessage,
		arg.ID,
		arg.TicketID,
		arg.Content,
		arg.IsAdmin,
		arg.CreatedAt,
	)
	return err
}

const listTicketImages = `-- name: ListTicketImages :many
SELECT id, ticket_id, filename, stored_name, size, created_at
FROM ticket_images WHERE ticket_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketImages(ctx context.Context, ticketID string) ([]TicketImage, error) {
	rows, err := q.db.Query(ctx, listTicketImages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketImage{}
	for rows.Next() {
		var i TicketImage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Filename,
			&i.StoredName,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT id, ticket_id, content, is_admin, created_at
FROM ticket_messages WHERE ticket_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTicketMessages(ctx context.Context, ticketID string) ([]TicketMessage, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketMessage{}
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Content,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, user_id, username, title, status, created_at, updated_at
FROM tickets ORDER BY updated_at DESC
`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUser = `-- name: ListTicketsByUser :many
SELECT id, user_id, username, title, status, created_at, updated_at
FROM tickets WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListTicketsByUser(ctx context.Context, userID string) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateTicketStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.Exec(ctx, updateTicketStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateTicketUpdatedAt = `-- name: UpdateTicketUpdatedAt :exec
UPDATE tickets SET updated_at = $1 WHERE id = $2
`

type UpdateTicketUpdatedAtParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateTicketUpdatedAt(ctx context.Context, arg UpdateTicketUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, updateTicketUpdatedAt, arg.UpdatedAt, arg.ID)
	return err
}
