// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usergroup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const addUserGroupMember = `-- name: AddUserGroupMember :exec
INSERT INTO user_group_members (group_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddUserGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) AddUserGroupMember(ctx context.Context, arg AddUserGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addUserGroupMember, arg.GroupID, arg.UserID)
	return err
}

const deleteAllUserGroupMembers = `-- name: DeleteAllUserGroupMembers :exec
DELETE FROM user_group_members WHERE group_id = $1
`

func (q *Queries) DeleteAllUserGroupMembers(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserGroupMembers, groupID)
	return err
}

const deleteUserGroupByID = `-- name: DeleteUserGroupByID :execresult
DELETE FROM user_groups WHERE id = $1
`

func (q *Queries) DeleteUserGroupByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUserGroupByID, id)
}

const getUserGroupByID = `-- name: GetUserGroupByID :one
SELECT id, name, remark, inbound_ids FROM user_groups WHERE id = $1
`

func (q *Queries) GetUserGroupByID(ctx context.Context, id string) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroupByID, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Remark,
		&i.InboundIds,
	)
	return i, err
}

const listUserGroupMembers = `-- name: ListUserGroupMembers :many
SELECT user_id FROM user_group_members WHERE group_id = $1 ORDER BY user_id
`

func (q *Queries) ListUserGroupMembers(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT id, name, remark, inbound_ids FROM user_groups ORDER BY name
`

func (q *Queries) ListUserGroups(ctx context.Context) ([]UserGroup, error) {
	rows, err := q.db.Query(ctx, listUserGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserGroup{}
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Remark,
			&i.InboundIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupsByUser = `-- name: ListUserGroupsByUser :many
SELECT group_id FROM user_group_members WHERE user_id = $1
`

func (q *Queries) ListUserGroupsByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_id string
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserGroupMember = `-- name: RemoveUserGroupMember :exec
DELETE FROM user_group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveUserGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) RemoveUserGroupMember(ctx context.Context, arg RemoveUserGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeUserGroupMember, arg.GroupID, arg.UserID)
	return err
}

const upsertUserGroup = `-- name: UpsertUserGroup :exec
INSERT INTO user_groups (id, name, remark, inbound_ids)
VALUES ($1, $2, $3, $4)
ON CONFLICT(id) DO UPDATE SET
    name        = excluded.name,
    remark      = excluded.remark,
    inbound_ids = excluded.inbound_ids
`

type UpsertUserGroupParams struct {
	ID         string
	Name       string
	Remark     string
	InboundIds string
}

func (q *Queries) UpsertUserGroup(ctx context.Context, arg UpsertUserGroupParams) error {
	_, err := q.db.Exec(ctx, upsertUserGroup,
		arg.ID,
		arg.Name,
		arg.Remark,
		arg.InboundIds,
	)
	return err
}
