// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const countUsersByInbound = `-- name: CountUsersByInbound :many
SELECT inbound_id, COUNT(DISTINCT user_id)::bigint AS count
FROM user_inbounds
GROUP BY inbound_id
`

type CountUsersByInboundRow struct {
	InboundID string
	Count     int64
}

func (q *Queries) CountUsersByInbound(ctx context.Context) ([]CountUsersByInboundRow, error) {
	rows, err := q.db.Query(ctx, countUsersByInbound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountUsersByInboundRow{}
	for rows.Next() {
		var i CountUsersByInboundRow
		if err := rows.Scan(&i.InboundID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllInboundsForGroup = `-- name: DeleteAllInboundsForGroup :exec
DELETE FROM user_inbounds WHERE group_id = $1
`

func (q *Queries) DeleteAllInboundsForGroup(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, deleteAllInboundsForGroup, groupID)
	return err
}

const deleteGroupUserInbounds = `-- name: DeleteGroupUserInbounds :exec
DELETE FROM user_inbounds WHERE user_id = $1 AND group_id = $2
`

type DeleteGroupUserInboundsParams struct {
	UserID  string
	GroupID string
}

func (q *Queries) DeleteGroupUserInbounds(ctx context.Context, arg DeleteGroupUserInboundsParams) error {
	_, err := q.db.Exec(ctx, deleteGroupUserInbounds, arg.UserID, arg.GroupID)
	return err
}

const deleteSubAccessLogsByUserID = `-- name: DeleteSubAccessLogsByUserID :exec
DELETE FROM sub_access_logs WHERE user_id = $1
`

func (q *Queries) DeleteSubAccessLogsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSubAccessLogsByUserID, userID)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :execresult
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUserByID, id)
}

const deleteUserInboundByID = `-- name: DeleteUserInboundByID :execresult
DELETE FROM user_inbounds WHERE id = $1
`

func (q *Queries) DeleteUserInboundByID(ctx context.Context, id string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUserInboundByID, id)
}

const deleteUserInboundsByUserID = `-- name: DeleteUserInboundsByUserID :exec
DELETE FROM user_inbounds WHERE user_id = $1
`

func (q *Queries) DeleteUserInboundsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserInboundsByUserID, userID)
	return err
}

const deleteUserInboundsByUserIDTx = `-- name: DeleteUserInboundsByUserIDTx :exec
DELETE FROM user_inbounds WHERE user_id = $1
`

func (q *Queries) DeleteUserInboundsByUserIDTx(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserInboundsByUserIDTx, userID)
	return err
}

const deleteUserNodeDailyUsageByUserID = `-- name: DeleteUserNodeDailyUsageByUserID :exec
DELETE FROM user_node_daily_usage WHERE user_id = $1
`

func (q *Queries) DeleteUserNodeDailyUsageByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserNodeDailyUsageByUserID, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, status, note, expire_at, data_limit_reset_strategy,
       traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
       raw_upload_bytes, raw_download_bytes,
       on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
       created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret, is_admin
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.Note,
		&i.ExpireAt,
		&i.DataLimitResetStrategy,
		&i.TrafficLimitBytes,
		&i.UploadBytes,
		&i.DownloadBytes,
		&i.UsedBytes,
		&i.RawUploadBytes,
		&i.RawDownloadBytes,
		&i.OnHoldExpireAt,
		&i.LastTrafficResetAt,
		&i.OnlineAt,
		&i.Connections,
		&i.Devices,
		&i.CreatedAt,
		&i.SubToken,
		&i.StripeCustomerID,
		&i.CurrentPlanID,
		&i.Email,
		&i.Uuid,
		&i.Secret,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, username, status, note, expire_at, data_limit_reset_strategy,
       traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
       raw_upload_bytes, raw_download_bytes,
       on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
       created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret, is_admin
FROM users
WHERE stripe_customer_id = $1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.Note,
		&i.ExpireAt,
		&i.DataLimitResetStrategy,
		&i.TrafficLimitBytes,
		&i.UploadBytes,
		&i.DownloadBytes,
		&i.UsedBytes,
		&i.RawUploadBytes,
		&i.RawDownloadBytes,
		&i.OnHoldExpireAt,
		&i.LastTrafficResetAt,
		&i.OnlineAt,
		&i.Connections,
		&i.Devices,
		&i.CreatedAt,
		&i.SubToken,
		&i.StripeCustomerID,
		&i.CurrentPlanID,
		&i.Email,
		&i.Uuid,
		&i.Secret,
		&i.IsAdmin,
	)
	return i, err
}

const getUserBySubToken = `-- name: GetUserBySubToken :one
SELECT id, username, status, note, expire_at, data_limit_reset_strategy,
       traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
       raw_upload_bytes, raw_download_bytes,
       on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
       created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret, is_admin
FROM users
WHERE sub_token = $1
`

func (q *Queries) GetUserBySubToken(ctx context.Context, subToken string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubToken, subToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Status,
		&i.Note,
		&i.ExpireAt,
		&i.DataLimitResetStrategy,
		&i.TrafficLimitBytes,
		&i.UploadBytes,
		&i.DownloadBytes,
		&i.UsedBytes,
		&i.RawUploadBytes,
		&i.RawDownloadBytes,
		&i.OnHoldExpireAt,
		&i.LastTrafficResetAt,
		&i.OnlineAt,
		&i.Connections,
		&i.Devices,
		&i.CreatedAt,
		&i.SubToken,
		&i.StripeCustomerID,
		&i.CurrentPlanID,
		&i.Email,
		&i.Uuid,
		&i.Secret,
		&i.IsAdmin,
	)
	return i, err
}

const getUserInboundByID = `-- name: GetUserInboundByID :one
SELECT id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id
FROM user_inbounds WHERE id = $1
`

func (q *Queries) GetUserInboundByID(ctx context.Context, id string) (UserInbound, error) {
	row := q.db.QueryRow(ctx, getUserInboundByID, id)
	var i UserInbound
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InboundID,
		&i.NodeID,
		&i.Uuid,
		&i.Secret,
		&i.CreatedAt,
		&i.GroupID,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, username, status, note, expire_at, data_limit_reset_strategy,
       traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
       raw_upload_bytes, raw_download_bytes,
       on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
       created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret, is_admin
FROM users
WHERE id = ANY($1::text[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.ExpireAt,
			&i.DataLimitResetStrategy,
			&i.TrafficLimitBytes,
			&i.UploadBytes,
			&i.DownloadBytes,
			&i.UsedBytes,
			&i.RawUploadBytes,
			&i.RawDownloadBytes,
			&i.OnHoldExpireAt,
			&i.LastTrafficResetAt,
			&i.OnlineAt,
			&i.Connections,
			&i.Devices,
			&i.CreatedAt,
			&i.SubToken,
			&i.StripeCustomerID,
			&i.CurrentPlanID,
			&i.Email,
			&i.Uuid,
			&i.Secret,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSubAccessLog = `-- name: InsertSubAccessLog :exec

INSERT INTO sub_access_logs (user_id, ip, user_agent, accessed_at)
VALUES ($1, $2, $3, $4)
`

type InsertSubAccessLogParams struct {
	UserID     string
	Ip         string
	UserAgent  string
	AccessedAt string
}

// ─── sub_access_logs ──────────────────────────────────────────────────────────
func (q *Queries) InsertSubAccessLog(ctx context.Context, arg InsertSubAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertSubAccessLog,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.AccessedAt,
	)
	return err
}

const listActiveUserInboundsByUser = `-- name: ListActiveUserInboundsByUser :many
SELECT ui.id, ui.user_id, ui.inbound_id, ui.node_id, ui.uuid, ui.secret, ui.created_at, ui.group_id
FROM user_inbounds ui
LEFT JOIN inbounds ib ON ui.inbound_id != '' AND ib.id = ui.inbound_id
LEFT JOIN nodes n ON n.id = COALESCE(NULLIF(ui.node_id, ''), ib.node_id)
WHERE ui.user_id = $1
AND (n.id IS NULL OR n.disabled = 0)
ORDER BY ui.id
`

func (q *Queries) ListActiveUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error) {
	rows, err := q.db.Query(ctx, listActiveUserInboundsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInbound{}
	for rows.Next() {
		var i UserInbound
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InboundID,
			&i.NodeID,
			&i.Uuid,
			&i.Secret,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectUserInboundsByUser = `-- name: ListDirectUserInboundsByUser :many
SELECT id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id
FROM user_inbounds WHERE user_id = $1 AND group_id = '' ORDER BY id
`

func (q *Queries) ListDirectUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error) {
	rows, err := q.db.Query(ctx, listDirectUserInboundsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInbound{}
	for rows.Next() {
		var i UserInbound
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InboundID,
			&i.NodeID,
			&i.Uuid,
			&i.Secret,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubAccessLogs = `-- name: ListSubAccessLogs :many
SELECT id, user_id, ip, user_agent, accessed_at
FROM sub_access_logs
WHERE user_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListSubAccessLogsParams struct {
	UserID string
	Limit  int32
}

func (q *Queries) ListSubAccessLogs(ctx context.Context, arg ListSubAccessLogsParams) ([]SubAccessLog, error) {
	rows, err := q.db.Query(ctx, listSubAccessLogs, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubAccessLog{}
	for rows.Next() {
		var i SubAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayNodeUserStats = `-- name: ListTodayNodeUserStats :many
SELECT u.username,
       SUM(d.upload_bytes)::bigint   AS upload_bytes,
       SUM(d.download_bytes)::bigint AS download_bytes
FROM user_node_daily_usage d
JOIN users u ON u.id = d.user_id
WHERE d.date = $1
  AND d.node_id = $2
GROUP BY d.user_id, u.username
HAVING SUM(d.upload_bytes) + SUM(d.download_bytes) > 0
ORDER BY SUM(d.upload_bytes) + SUM(d.download_bytes) DESC
LIMIT $3
`

type ListTodayNodeUserStatsParams struct {
	Date   string
	NodeID string
	Limit  int32
}

type ListTodayNodeUserStatsRow struct {
	Username      string
	UploadBytes   int64
	DownloadBytes int64
}

func (q *Queries) ListTodayNodeUserStats(ctx context.Context, arg ListTodayNodeUserStatsParams) ([]ListTodayNodeUserStatsRow, error) {
	rows, err := q.db.Query(ctx, listTodayNodeUserStats, arg.Date, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodayNodeUserStatsRow{}
	for rows.Next() {
		var i ListTodayNodeUserStatsRow
		if err := rows.Scan(&i.Username, &i.UploadBytes, &i.DownloadBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayUserNodeStats = `-- name: ListTodayUserNodeStats :many
SELECT n.id   AS node_id,
       n.name AS node_name,
       SUM(d.upload_bytes)::bigint   AS upload_bytes,
       SUM(d.download_bytes)::bigint AS download_bytes
FROM user_node_daily_usage d
JOIN users u ON u.id = d.user_id
JOIN nodes n ON n.id = d.node_id
WHERE d.date = $1
  AND u.username = $2
GROUP BY n.id, n.name
HAVING SUM(d.upload_bytes) + SUM(d.download_bytes) > 0
ORDER BY SUM(d.upload_bytes) + SUM(d.download_bytes) DESC
`

type ListTodayUserNodeStatsParams struct {
	Date     string
	Username string
}

type ListTodayUserNodeStatsRow struct {
	NodeID        string
	NodeName      string
	UploadBytes   int64
	DownloadBytes int64
}

func (q *Queries) ListTodayUserNodeStats(ctx context.Context, arg ListTodayUserNodeStatsParams) ([]ListTodayUserNodeStatsRow, error) {
	rows, err := q.db.Query(ctx, listTodayUserNodeStats, arg.Date, arg.Username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodayUserNodeStatsRow{}
	for rows.Next() {
		var i ListTodayUserNodeStatsRow
		if err := rows.Scan(
			&i.NodeID,
			&i.NodeName,
			&i.UploadBytes,
			&i.DownloadBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayUserStats = `-- name: ListTodayUserStats :many
SELECT u.username,
       SUM(d.upload_bytes)::bigint   AS upload_bytes,
       SUM(d.download_bytes)::bigint AS download_bytes
FROM user_node_daily_usage d
JOIN users u ON u.id = d.user_id
WHERE d.date = $1
GROUP BY d.user_id, u.username
HAVING SUM(d.upload_bytes) + SUM(d.download_bytes) > 0
ORDER BY SUM(d.upload_bytes) + SUM(d.download_bytes) DESC
LIMIT $2
`

type ListTodayUserStatsParams struct {
	Date  string
	Limit int32
}

type ListTodayUserStatsRow struct {
	Username      string
	UploadBytes   int64
	DownloadBytes int64
}

func (q *Queries) ListTodayUserStats(ctx context.Context, arg ListTodayUserStatsParams) ([]ListTodayUserStatsRow, error) {
	rows, err := q.db.Query(ctx, listTodayUserStats, arg.Date, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodayUserStatsRow{}
	for rows.Next() {
		var i ListTodayUserStatsRow
		if err := rows.Scan(&i.Username, &i.UploadBytes, &i.DownloadBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDailyUsage = `-- name: ListUserDailyUsage :many
SELECT date, SUM(upload_bytes)::bigint AS upload_bytes, SUM(download_bytes)::bigint AS download_bytes
FROM user_node_daily_usage
WHERE user_id = $1 AND date >= $2
GROUP BY date
ORDER BY date
`

type ListUserDailyUsageParams struct {
	UserID string
	Date   string
}

type ListUserDailyUsageRow struct {
	Date          string
	UploadBytes   int64
	DownloadBytes int64
}

func (q *Queries) ListUserDailyUsage(ctx context.Context, arg ListUserDailyUsageParams) ([]ListUserDailyUsageRow, error) {
	rows, err := q.db.Query(ctx, listUserDailyUsage, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDailyUsageRow{}
	for rows.Next() {
		var i ListUserDailyUsageRow
		if err := rows.Scan(&i.Date, &i.UploadBytes, &i.DownloadBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInboundsByInbound = `-- name: ListUserInboundsByInbound :many
SELECT id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id
FROM user_inbounds WHERE inbound_id = $1 ORDER BY id
`

func (q *Queries) ListUserInboundsByInbound(ctx context.Context, inboundID string) ([]UserInbound, error) {
	rows, err := q.db.Query(ctx, listUserInboundsByInbound, inboundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInbound{}
	for rows.Next() {
		var i UserInbound
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InboundID,
			&i.NodeID,
			&i.Uuid,
			&i.Secret,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInboundsByNode = `-- name: ListUserInboundsByNode :many
SELECT id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id
FROM user_inbounds WHERE node_id = $1 ORDER BY id
`

func (q *Queries) ListUserInboundsByNode(ctx context.Context, nodeID string) ([]UserInbound, error) {
	rows, err := q.db.Query(ctx, listUserInboundsByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInbound{}
	for rows.Next() {
		var i UserInbound
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InboundID,
			&i.NodeID,
			&i.Uuid,
			&i.Secret,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInboundsByUser = `-- name: ListUserInboundsByUser :many
SELECT id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id
FROM user_inbounds WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListUserInboundsByUser(ctx context.Context, userID string) ([]UserInbound, error) {
	rows, err := q.db.Query(ctx, listUserInboundsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserInbound{}
	for rows.Next() {
		var i UserInbound
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InboundID,
			&i.NodeID,
			&i.Uuid,
			&i.Secret,
			&i.CreatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNodeUsage = `-- name: ListUserNodeUsage :many
SELECT node_id,
       SUM(upload_bytes)::bigint   AS upload_bytes,
       SUM(download_bytes)::bigint AS download_bytes
FROM user_node_daily_usage
WHERE user_id = $1
GROUP BY node_id
ORDER BY SUM(upload_bytes) + SUM(download_bytes) DESC
`

type ListUserNodeUsageRow struct {
	NodeID        string
	UploadBytes   int64
	DownloadBytes int64
}

func (q *Queries) ListUserNodeUsage(ctx context.Context, userID string) ([]ListUserNodeUsageRow, error) {
	rows, err := q.db.Query(ctx, listUserNodeUsage, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNodeUsageRow{}
	for rows.Next() {
		var i ListUserNodeUsageRow
		if err := rows.Scan(&i.NodeID, &i.UploadBytes, &i.DownloadBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, status, note, expire_at, data_limit_reset_strategy,
       traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
       raw_upload_bytes, raw_download_bytes,
       on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
       created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret, is_admin
FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Status,
			&i.Note,
			&i.ExpireAt,
			&i.DataLimitResetStrategy,
			&i.TrafficLimitBytes,
			&i.UploadBytes,
			&i.DownloadBytes,
			&i.UsedBytes,
			&i.RawUploadBytes,
			&i.RawDownloadBytes,
			&i.OnHoldExpireAt,
			&i.LastTrafficResetAt,
			&i.OnlineAt,
			&i.Connections,
			&i.Devices,
			&i.CreatedAt,
			&i.SubToken,
			&i.StripeCustomerID,
			&i.CurrentPlanID,
			&i.Email,
			&i.Uuid,
			&i.Secret,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserCredentials = `-- name: SetUserCredentials :exec
UPDATE users SET uuid = $2, secret = $3 WHERE id = $1
`

type SetUserCredentialsParams struct {
	ID     string
	Uuid   string
	Secret string
}

func (q *Queries) SetUserCredentials(ctx context.Context, arg SetUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, setUserCredentials, arg.ID, arg.Uuid, arg.Secret)
	return err
}

const trimSubAccessLogsByUser = `-- name: TrimSubAccessLogsByUser :exec
DELETE FROM sub_access_logs AS sal
WHERE sal.user_id = $1
  AND sal.id NOT IN (
    SELECT id FROM sub_access_logs
    WHERE user_id = $1
    ORDER BY id DESC
    LIMIT $2
  )
`

type TrimSubAccessLogsByUserParams struct {
	UserID string
	Limit  int32
}

// 插入后调用，保留每个用户最近 $2 条，超出部分按 id 升序删除（即最旧的先删）
func (q *Queries) TrimSubAccessLogsByUser(ctx context.Context, arg TrimSubAccessLogsByUserParams) error {
	_, err := q.db.Exec(ctx, trimSubAccessLogsByUser, arg.UserID, arg.Limit)
	return err
}

const updateUserInboundsNodeID = `-- name: UpdateUserInboundsNodeID :exec
UPDATE user_inbounds SET node_id = $1 WHERE inbound_id = $2
`

type UpdateUserInboundsNodeIDParams struct {
	NodeID    string
	InboundID string
}

func (q *Queries) UpdateUserInboundsNodeID(ctx context.Context, arg UpdateUserInboundsNodeIDParams) error {
	_, err := q.db.Exec(ctx, updateUserInboundsNodeID, arg.NodeID, arg.InboundID)
	return err
}

const upsertGroupUserInbound = `-- name: UpsertGroupUserInbound :exec
INSERT INTO user_inbounds (id, user_id, inbound_id, node_id, uuid, secret, group_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(id) DO UPDATE SET
    inbound_id = excluded.inbound_id,
    node_id    = excluded.node_id,
    uuid       = excluded.uuid,
    secret     = excluded.secret,
    group_id   = excluded.group_id
`

type UpsertGroupUserInboundParams struct {
	ID        string
	UserID    string
	InboundID string
	NodeID    string
	Uuid      string
	Secret    string
	GroupID   string
	CreatedAt string
}

func (q *Queries) UpsertGroupUserInbound(ctx context.Context, arg UpsertGroupUserInboundParams) error {
	_, err := q.db.Exec(ctx, upsertGroupUserInbound,
		arg.ID,
		arg.UserID,
		arg.InboundID,
		arg.NodeID,
		arg.Uuid,
		arg.Secret,
		arg.GroupID,
		arg.CreatedAt,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec

INSERT INTO users (
    id, username, status, note, expire_at, data_limit_reset_strategy,
    traffic_limit_bytes, upload_bytes, download_bytes, used_bytes,
    raw_upload_bytes, raw_download_bytes,
    on_hold_expire_at, last_traffic_reset_at, online_at, connections, devices,
    created_at, sub_token, stripe_customer_id, current_plan_id, email, uuid, secret
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)
ON CONFLICT(id) DO UPDATE SET
    username                  = excluded.username,
    status                    = excluded.status,
    note                      = excluded.note,
    expire_at                 = excluded.expire_at,
    data_limit_reset_strategy = excluded.data_limit_reset_strategy,
    traffic_limit_bytes       = excluded.traffic_limit_bytes,
    upload_bytes              = excluded.upload_bytes,
    download_bytes            = excluded.download_bytes,
    used_bytes                = excluded.used_bytes,
    raw_upload_bytes          = excluded.raw_upload_bytes,
    raw_download_bytes        = excluded.raw_download_bytes,
    on_hold_expire_at         = excluded.on_hold_expire_at,
    last_traffic_reset_at     = excluded.last_traffic_reset_at,
    online_at                 = excluded.online_at,
    connections               = excluded.connections,
    devices                   = excluded.devices,
    created_at                = excluded.created_at,
    sub_token                 = excluded.sub_token,
    stripe_customer_id        = excluded.stripe_customer_id,
    current_plan_id           = excluded.current_plan_id,
    email                     = excluded.email,
    uuid                      = excluded.uuid,
    secret                    = excluded.secret
`

type UpsertUserParams struct {
	ID                     string
	Username               string
	Status                 string
	Note                   string
	ExpireAt               *string
	DataLimitResetStrategy string
	TrafficLimitBytes      int64
	UploadBytes            int64
	DownloadBytes          int64
	UsedBytes              int64
	RawUploadBytes         int64
	RawDownloadBytes       int64
	OnHoldExpireAt         *string
	LastTrafficResetAt     *string
	OnlineAt               *string
	Connections            int64
	Devices                int64
	CreatedAt              string
	SubToken               string
	StripeCustomerID       string
	CurrentPlanID          string
	Email                  string
	Uuid                   string
	Secret                 string
}

// ─── Users ────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.Status,
		arg.Note,
		arg.ExpireAt,
		arg.DataLimitResetStrategy,
		arg.TrafficLimitBytes,
		arg.UploadBytes,
		arg.DownloadBytes,
		arg.UsedBytes,
		arg.RawUploadBytes,
		arg.RawDownloadBytes,
		arg.OnHoldExpireAt,
		arg.LastTrafficResetAt,
		arg.OnlineAt,
		arg.Connections,
		arg.Devices,
		arg.CreatedAt,
		arg.SubToken,
		arg.StripeCustomerID,
		arg.CurrentPlanID,
		arg.Email,
		arg.Uuid,
		arg.Secret,
	)
	return err
}

const upsertUserInbound = `-- name: UpsertUserInbound :exec

INSERT INTO user_inbounds (id, user_id, inbound_id, node_id, uuid, secret, created_at, group_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(id) DO UPDATE SET
    user_id    = excluded.user_id,
    inbound_id = excluded.inbound_id,
    node_id    = excluded.node_id,
    uuid       = excluded.uuid,
    secret     = excluded.secret,
    created_at = excluded.created_at,
    group_id   = excluded.group_id
`

type UpsertUserInboundParams struct {
	ID        string
	UserID    string
	InboundID string
	NodeID    string
	Uuid      string
	Secret    string
	CreatedAt string
	GroupID   string
}

// ─── UserInbounds ─────────────────────────────────────────────────────────────
func (q *Queries) UpsertUserInbound(ctx context.Context, arg UpsertUserInboundParams) error {
	_, err := q.db.Exec(ctx, upsertUserInbound,
		arg.ID,
		arg.UserID,
		arg.InboundID,
		arg.NodeID,
		arg.Uuid,
		arg.Secret,
		arg.CreatedAt,
		arg.GroupID,
	)
	return err
}

const upsertUserNodeTraffic = `-- name: UpsertUserNodeTraffic :exec

INSERT INTO user_node_daily_usage (user_id, node_id, date, upload_bytes, download_bytes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(user_id, node_id, date) DO UPDATE SET
    upload_bytes   = user_node_daily_usage.upload_bytes   + excluded.upload_bytes,
    download_bytes = user_node_daily_usage.download_bytes + excluded.download_bytes
`

type UpsertUserNodeTrafficParams struct {
	UserID        string
	NodeID        string
	Date          string
	UploadBytes   int64
	DownloadBytes int64
}

// ─── user_node_daily_usage ────────────────────────────────────────────────────
func (q *Queries) UpsertUserNodeTraffic(ctx context.Context, arg UpsertUserNodeTrafficParams) error {
	_, err := q.db.Exec(ctx, upsertUserNodeTraffic,
		arg.UserID,
		arg.NodeID,
		arg.Date,
		arg.UploadBytes,
		arg.DownloadBytes,
	)
	return err
}
